# Generated by Django 5.2.17 on 2026-08-11 00:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("suppliers", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("po_number", models.CharField(db_index=True, max_length=60, verbose_name="PO Number")),
                (
                    "supplier_reference",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Supplier Quote / Ref No."),
                ),
                ("order_date", models.DateField(verbose_name="Order Date")),
                (
                    "expected_delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="Expected Delivery Date"),
                ),
                ("actual_delivery_date", models.DateField(blank=True, null=True, verbose_name="Actual Delivery Date")),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        max_digits=12,
                        verbose_name="Exchange Rate to Base Currency",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="Net 30", max_length=100, verbose_name="Payment Terms"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("sent_to_supplier", "Sent to Supplier"),
                            ("acknowledged", "Acknowledged by Supplier"),
                            ("partially_received", "Partially Received"),
                            ("fully_received", "Fully Received"),
                            ("cancelled", "Cancelled"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="PO Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("emergency", "Emergency Purchase"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount Amount"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Shipping Cost"
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Other Charges"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Grand Total"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, default="", verbose_name="Terms and Conditions"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Sent To Supplier At")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="Acknowledged At")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At")),
                ("cancellation_reason", models.TextField(blank=True, default="", verbose_name="Cancellation Reason")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled By",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="warehouses.warehouse",
                        verbose_name="Destination Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "procurement_purchase_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderAmendment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("amendment_number", models.CharField(db_index=True, max_length=60, verbose_name="Amendment Number")),
                ("reason", models.TextField(verbose_name="Amendment Reason")),
                ("changed_fields", models.JSONField(default=dict, verbose_name="Changed Fields (Previous vs New)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="approved",
                        max_length=30,
                        verbose_name="Amendment Status",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_amendments_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_amendments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="procurement.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Amendment",
                "verbose_name_plural": "Purchase Order Amendments",
                "db_table": "procurement_po_amendments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "supplier_product_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Supplier SKU / Product Code"
                    ),
                ),
                (
                    "supplier_barcode",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Supplier Barcode"),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Line Description"),
                ),
                (
                    "ordered_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Ordered Quantity"
                    ),
                ),
                (
                    "free_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Free Bonus Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Purchase Price"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Discount Percentage"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount Amount"
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6, verbose_name="Tax Percentage"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Subtotal"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Grand Total"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Received Quantity"
                    ),
                ),
                (
                    "free_quantity_received",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Free Quantity Received",
                    ),
                ),
                ("expected_date", models.DateField(blank=True, null=True, verbose_name="Expected Line Date")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location Foundation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_order_lines",
                        to="warehouses.warehouse",
                        verbose_name="Line Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Line",
                "verbose_name_plural": "Purchase Order Lines",
                "db_table": "procurement_purchase_order_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "requisition_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Requisition Number"),
                ),
                ("department", models.CharField(blank=True, default="", max_length=100, verbose_name="Department")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("emergency", "Emergency Purchase"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock Replenishment"),
                            ("out_of_stock", "Out of Stock Urgent Need"),
                            ("expiry_replacement", "Expiry Batch Replacement"),
                            ("new_product", "New Product Introduction"),
                            ("regular_replenishment", "Regular Replenishment Cycle"),
                            ("customer_request", "Customer Special Request"),
                            ("emergency", "Emergency Supply Request"),
                            ("manual", "Manual Purchasing Order"),
                            ("other", "Other Reason"),
                        ],
                        default="regular_replenishment",
                        max_length=40,
                        verbose_name="Requisition Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("converted_to_po", "Converted to PO"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Requisition Status",
                    ),
                ),
                ("required_date", models.DateField(blank=True, null=True, verbose_name="Required Date")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("rejected_at", models.DateTimeField(blank=True, null=True, verbose_name="Rejected At")),
                ("rejection_reason", models.TextField(blank=True, default="", verbose_name="Rejection Reason")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "total_estimated_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Estimated Cost"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requisitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_requisitions",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requisitions",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_requisitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rejected By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_requisitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requisitions",
                        to="warehouses.warehouse",
                        verbose_name="Target Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Requisition",
                "verbose_name_plural": "Purchase Requisitions",
                "db_table": "procurement_requisitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="procurement.purchaserequisition",
                verbose_name="Source Requisition",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "requested_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Requested Quantity"
                    ),
                ),
                (
                    "approved_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Approved Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "estimated_unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Estimated Unit Cost"
                    ),
                ),
                (
                    "estimated_total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Estimated Total Cost"
                    ),
                ),
                ("required_date", models.DateField(blank=True, null=True, verbose_name="Required Date")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisition_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requisition_lines",
                        to="suppliers.supplier",
                        verbose_name="Preferred Supplier",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.purchaserequisition",
                        verbose_name="Purchase Requisition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Requisition Line",
                "verbose_name_plural": "Purchase Requisition Lines",
                "db_table": "procurement_requisition_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProductPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "supplier_sku",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Supplier SKU"),
                ),
                (
                    "supplier_barcode",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Supplier Barcode"),
                ),
                (
                    "last_purchase_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Last Purchase Price"
                    ),
                ),
                (
                    "current_contract_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Current Contract Price",
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=14,
                        verbose_name="Minimum Order Quantity",
                    ),
                ),
                (
                    "maximum_order_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True, verbose_name="Maximum Order Quantity"
                    ),
                ),
                ("is_preferred_supplier", models.BooleanField(default=False, verbose_name="Is Preferred Supplier")),
                ("lead_time_days", models.PositiveIntegerField(default=3, verbose_name="Lead Time (Days)")),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                ("effective_date", models.DateField(blank=True, null=True, verbose_name="Effective Date")),
                ("expiry_date", models.DateField(blank=True, null=True, verbose_name="Contract Expiry Date")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_prices",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Product Price",
                "verbose_name_plural": "Supplier Product Prices",
                "db_table": "procurement_supplier_prices",
                "ordering": ["supplier", "medicine"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("quotation_number", models.CharField(db_index=True, max_length=60, verbose_name="Quotation Number")),
                ("validity_date", models.DateField(blank=True, null=True, verbose_name="Validity Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Quotation",
                "verbose_name_plural": "Supplier Quotations",
                "db_table": "procurement_supplier_quotations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuotationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Quantity"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Price"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=3, verbose_name="Lead Time Days")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="procurement.supplierquotation",
                        verbose_name="Supplier Quotation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Quotation Line",
                "verbose_name_plural": "Supplier Quotation Lines",
                "db_table": "procurement_supplier_quotation_lines",
            },
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(fields=["tenant", "status"], name="procurement_tenant__f0e1ba_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaserequisition",
            index=models.Index(fields=["tenant", "warehouse"], name="procurement_tenant__7be441_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisition",
            constraint=models.UniqueConstraint(
                fields=("tenant", "requisition_number"), name="purchase_requisition_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["tenant", "status"], name="procurement_tenant__db5195_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["tenant", "supplier"], name="procurement_tenant__6a55b5_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["tenant", "warehouse"], name="procurement_tenant__019fd7_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(fields=["tenant", "order_date"], name="procurement_tenant__ae05bd_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("tenant", "po_number"), name="purchase_order_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproductprice",
            index=models.Index(fields=["tenant", "supplier"], name="procurement_tenant__ff2006_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproductprice",
            index=models.Index(fields=["tenant", "medicine"], name="procurement_tenant__f3e5f6_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierproductprice",
            index=models.Index(fields=["tenant", "is_active"], name="procurement_tenant__5d3d83_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierproductprice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "supplier", "medicine"), name="supplier_product_price_tenant_uniq"
            ),
        ),
    ]
