# Generated by Django 5.2.17 on 2026-08-07 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Medicine code")),
                ("sku", models.CharField(max_length=100, verbose_name="SKU")),
                (
                    "barcode",
                    models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="Barcode"),
                ),
                ("qr_code", models.CharField(blank=True, default="", max_length=255, verbose_name="QR code")),
                ("arabic_name", models.CharField(max_length=255, verbose_name="Arabic name")),
                ("english_name", models.CharField(max_length=255, verbose_name="English name")),
                (
                    "generic_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Generic name"),
                ),
                (
                    "scientific_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Scientific name"),
                ),
                ("brand_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Brand name")),
                ("short_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Short name")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="medicine_images/", verbose_name="Image"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("discontinued", "Discontinued"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "therapeutic_class",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Therapeutic class"),
                ),
                (
                    "pharmacological_class",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Pharmacological class"),
                ),
                ("atc_code", models.CharField(blank=True, default="", max_length=50, verbose_name="ATC code")),
                ("category", models.CharField(blank=True, default="", max_length=100, verbose_name="Category")),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("otc", "Over The Counter (OTC)"),
                            ("prescription_only", "Prescription Only (Rx)"),
                            ("controlled", "Controlled Drug"),
                            ("narcotic", "Narcotic"),
                        ],
                        default="prescription_only",
                        max_length=30,
                        verbose_name="Prescription type",
                    ),
                ),
                (
                    "controlled_drug_schedule",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Controlled drug schedule"),
                ),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("allopathic", "Allopathic"),
                            ("herbal", "Herbal"),
                            ("homeopathic", "Homeopathic"),
                            ("supplement", "Nutritional Supplement"),
                            ("medical_device", "Medical Device"),
                        ],
                        default="allopathic",
                        max_length=30,
                        verbose_name="Medicine type",
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Manufacturer name"),
                ),
                (
                    "country_of_origin",
                    models.CharField(default="Yemen", max_length=100, verbose_name="Country of origin"),
                ),
                (
                    "marketing_company",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Marketing company"),
                ),
                (
                    "registration_authority",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Registration authority"),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Registration number"),
                ),
                ("dosage_form", models.CharField(default="Tablet", max_length=100, verbose_name="Dosage form")),
                ("strength", models.CharField(blank=True, default="", max_length=50, verbose_name="Strength")),
                (
                    "strength_unit",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Strength unit"),
                ),
                (
                    "concentration",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Concentration"),
                ),
                (
                    "route_of_administration",
                    models.CharField(default="Oral", max_length=100, verbose_name="Route of administration"),
                ),
                ("package_size", models.PositiveIntegerField(default=1, verbose_name="Package size")),
                ("package_type", models.CharField(default="Box", max_length=50, verbose_name="Package type")),
                ("unit_of_measure", models.CharField(default="Pcs", max_length=30, verbose_name="Unit of measure")),
                (
                    "minimum_dispensing_unit",
                    models.CharField(default="Pcs", max_length=30, verbose_name="Minimum dispensing unit"),
                ),
                ("indications", models.TextField(blank=True, default="", verbose_name="Indications")),
                ("contraindications", models.TextField(blank=True, default="", verbose_name="Contraindications")),
                ("warnings", models.TextField(blank=True, default="", verbose_name="Warnings")),
                ("side_effects", models.TextField(blank=True, default="", verbose_name="Side effects")),
                (
                    "storage_conditions",
                    models.CharField(
                        default="Store below 25°C in a dry place", max_length=200, verbose_name="Storage conditions"
                    ),
                ),
                (
                    "pregnancy_category",
                    models.CharField(
                        choices=[
                            ("A", "Category A - Controlled studies show no risk"),
                            ("B", "Category B - No evidence of risk in humans"),
                            ("C", "Category C - Risk cannot be ruled out"),
                            ("D", "Category D - Positive evidence of risk"),
                            ("X", "Category X - Contraindicated in pregnancy"),
                            ("N", "Category N - Not classified"),
                        ],
                        default="N",
                        max_length=10,
                        verbose_name="Pregnancy category",
                    ),
                ),
                ("lactation_warning", models.TextField(blank=True, default="", verbose_name="Lactation warning")),
                ("pediatric_usage", models.TextField(blank=True, default="", verbose_name="Pediatric usage")),
                ("geriatric_usage", models.TextField(blank=True, default="", verbose_name="Geriatric usage")),
                ("is_high_alert", models.BooleanField(default=False, verbose_name="High alert drug")),
                ("is_lasa", models.BooleanField(default=False, verbose_name="LASA drug")),
                ("is_narcotic", models.BooleanField(default=False, verbose_name="Narcotic drug")),
                ("is_psychotropic", models.BooleanField(default=False, verbose_name="Psychotropic drug")),
                ("is_refrigerated", models.BooleanField(default=False, verbose_name="Refrigerated storage")),
                ("is_hazardous", models.BooleanField(default=False, verbose_name="Hazardous drug")),
                (
                    "default_purchase_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Default purchase price"
                    ),
                ),
                (
                    "default_selling_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Default selling price"
                    ),
                ),
                ("tax_category", models.CharField(default="standard", max_length=50, verbose_name="Tax category")),
                (
                    "default_profit_margin",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, verbose_name="Default profit margin %"
                    ),
                ),
                ("is_insurance_eligible", models.BooleanField(default=True, verbose_name="Insurance eligible")),
                ("is_discount_eligible", models.BooleanField(default=True, verbose_name="Discount eligible")),
                ("is_return_eligible", models.BooleanField(default=True, verbose_name="Return eligible")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicines",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicines",
                "ordering": ["english_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="medicines_medicine_tenant_code_uniq"),
                    models.UniqueConstraint(fields=("tenant", "sku"), name="medicines_medicine_tenant_sku_uniq"),
                ],
            },
        ),
    ]
