# Generated by Django 5.2.17 on 2026-08-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="approval_date",
            field=models.DateField(blank=True, null=True, verbose_name="Approval date"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="breastfeeding_safety",
            field=models.TextField(blank=True, default="", verbose_name="Breastfeeding safety"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="commercial_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Commercial name"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="drug_classification",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="Drug classification"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="drug_family",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="Drug family"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="expiry_of_registration",
            field=models.DateField(blank=True, null=True, verbose_name="Expiry of registration"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_cold_chain_required",
            field=models.BooleanField(default=False, verbose_name="Cold chain required"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_controlled_substance",
            field=models.BooleanField(default=False, verbose_name="Controlled substance"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_light_sensitive",
            field=models.BooleanField(default=False, verbose_name="Light sensitive"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="is_price_editable",
            field=models.BooleanField(default=True, verbose_name="Price editable"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="maximum_daily_dose",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Maximum daily dose"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="precautions",
            field=models.TextField(blank=True, default="", verbose_name="Precautions"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="search_keywords",
            field=models.TextField(blank=True, default="", verbose_name="Search keywords"),
        ),
        migrations.AddField(
            model_name="medicine",
            name="suggested_retail_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Suggested retail price"
            ),
        ),
    ]
