# Generated by Django 5.2.17 on 2026-08-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0002_medicine_approval_date_medicine_breastfeeding_safety_and_more"),
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="references.medicinecategory",
                verbose_name="Category Reference",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="dosage_form_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="references.dosageform",
                verbose_name="Dosage Form Reference",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="manufacturer_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="references.manufacturer",
                verbose_name="Manufacturer Reference",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="tax_category_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="references.taxcategory",
                verbose_name="Tax Category Reference",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="unit_of_measure_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicines",
                to="references.unitofmeasure",
                verbose_name="Unit of Measure Reference",
            ),
        ),
    ]
