# Generated by Django 5.2.17 on 2026-08-09 23:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("transfer_number", models.CharField(db_index=True, max_length=100, verbose_name="Transfer Number")),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("location_transfer", "Storage Location Transfer"),
                            ("warehouse_transfer", "Warehouse Transfer"),
                            ("branch_transfer", "Inter-Branch Transfer"),
                            ("emergency_transfer", "Emergency Transfer"),
                            ("return_transfer", "Return Transfer"),
                            ("quarantine_transfer", "Quarantine Transfer"),
                            ("other", "Other Transfer"),
                        ],
                        db_index=True,
                        default="warehouse_transfer",
                        max_length=50,
                        verbose_name="Transfer Type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent / Emergency"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("requested", "Requested"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("picking", "Picking In Progress"),
                            ("ready_for_dispatch", "Ready for Dispatch"),
                            ("dispatched", "Dispatched"),
                            ("in_transit", "In Transit"),
                            ("partially_received", "Partially Received"),
                            ("received", "Fully Received"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("discrepancy", "Discrepancy Reported"),
                            ("closed", "Closed / Completed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=50,
                        verbose_name="Transfer Status",
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True, verbose_name="Requested Timestamp")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved Timestamp")),
                ("dispatched_at", models.DateTimeField(blank=True, null=True, verbose_name="Dispatched Timestamp")),
                ("received_at", models.DateTimeField(blank=True, null=True, verbose_name="Received Timestamp")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled Timestamp")),
                (
                    "expected_arrival_date",
                    models.DateField(blank=True, null=True, verbose_name="Expected Arrival Date"),
                ),
                ("actual_arrival_date", models.DateField(blank=True, null=True, verbose_name="Actual Arrival Date")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Reason")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("reference_type", models.CharField(blank=True, max_length=50, verbose_name="Reference Type")),
                ("reference_id", models.CharField(blank=True, max_length=100, verbose_name="Reference ID")),
                ("total_items", models.IntegerField(default=0, verbose_name="Total Items Count")),
                (
                    "total_requested_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Total Requested Quantity",
                    ),
                ),
                (
                    "total_dispatched_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Total Dispatched Quantity",
                    ),
                ),
                (
                    "total_received_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Total Received Quantity",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Transfer Cost"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=100, verbose_name="Idempotency Key"),
                ),
                (
                    "has_discrepancy",
                    models.BooleanField(db_index=True, default=False, verbose_name="Has Discrepancy Flag"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cancelled By",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transfers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "destination_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_transfers",
                        to="branches.branch",
                        verbose_name="Destination Branch",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_location_transfers",
                        to="warehouses.storagelocation",
                        verbose_name="Destination Storage Location",
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_transfers",
                        to="warehouses.warehouse",
                        verbose_name="Destination Warehouse",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dispatched By",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_stock_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "source_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_transfers",
                        to="branches.branch",
                        verbose_name="Source Branch",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_location_transfers",
                        to="warehouses.storagelocation",
                        verbose_name="Source Storage Location",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_transfers",
                        to="warehouses.warehouse",
                        verbose_name="Source Warehouse",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transfer",
                "verbose_name_plural": "Stock Transfers",
                "db_table": "stock_transfer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(db_index=True, max_length=100, verbose_name="Event Type")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Timestamp")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Event Details")),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "stock_transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock_transfer.stocktransfer",
                        verbose_name="Stock Transfer Document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transfer History",
                "verbose_name_plural": "Stock Transfer History Log",
                "db_table": "stock_transfer_history",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "requested_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Requested Quantity"
                    ),
                ),
                (
                    "approved_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Approved Quantity"
                    ),
                ),
                (
                    "picked_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Picked Quantity"
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Dispatched Quantity"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Received Quantity"
                    ),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Rejected Quantity"
                    ),
                ),
                (
                    "damaged_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Damaged Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Cost"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Line Cost"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("picked", "Picked"),
                            ("dispatched", "Dispatched"),
                            ("received", "Received"),
                            ("partial", "Partially Received"),
                            ("rejected", "Rejected"),
                            ("damaged", "Damaged"),
                            ("discrepancy", "Discrepancy Reported"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=50,
                        verbose_name="Line Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Line Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_lines",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_line_transfers",
                        to="warehouses.storagelocation",
                        verbose_name="Destination Storage Location",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_line_transfers",
                        to="warehouses.storagelocation",
                        verbose_name="Source Storage Location",
                    ),
                ),
                (
                    "stock_transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock_transfer.stocktransfer",
                        verbose_name="Stock Transfer Document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transfer Line",
                "verbose_name_plural": "Stock Transfer Lines",
                "db_table": "stock_transfer_line",
                "ordering": ["stock_transfer", "medicine"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferDiscrepancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "discrepancy_number",
                    models.CharField(db_index=True, max_length=100, verbose_name="Discrepancy Number"),
                ),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("shortage", "Quantity Shortage"),
                            ("overage", "Quantity Overage"),
                            ("damage", "Damaged Goods"),
                            ("wrong_batch", "Wrong Batch Received"),
                            ("wrong_medicine", "Wrong Medicine Received"),
                            ("wrong_quantity", "Wrong Quantity"),
                            ("missing_item", "Missing Item"),
                            ("other", "Other Discrepancy"),
                        ],
                        db_index=True,
                        default="shortage",
                        max_length=50,
                        verbose_name="Discrepancy Type",
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Expected Quantity"
                    ),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Actual Quantity"
                    ),
                ),
                (
                    "difference_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Difference Quantity"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Discrepancy Reason")),
                ("evidence", models.TextField(blank=True, verbose_name="Evidence / Observations")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="reported",
                        max_length=50,
                        verbose_name="Discrepancy Status",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="Resolution Notes")),
                ("resolution_date", models.DateTimeField(blank=True, null=True, verbose_name="Resolution Date")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "expected_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expected_discrepancies",
                        to="inventory.batch",
                        verbose_name="Expected Batch",
                    ),
                ),
                (
                    "expected_medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expected_discrepancies",
                        to="medicines.medicine",
                        verbose_name="Expected Medicine",
                    ),
                ),
                (
                    "received_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_discrepancies",
                        to="inventory.batch",
                        verbose_name="Received Batch",
                    ),
                ),
                (
                    "received_medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_discrepancies",
                        to="medicines.medicine",
                        verbose_name="Received Medicine",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "stock_transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="stock_transfer.stocktransfer",
                        verbose_name="Stock Transfer Document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "transfer_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancies",
                        to="stock_transfer.stocktransferline",
                        verbose_name="Stock Transfer Line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Transfer Discrepancy",
                "verbose_name_plural": "Stock Transfer Discrepancies",
                "db_table": "stock_transfer_discrepancy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["tenant", "status"], name="stock_trans_tenant__7fa205_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["tenant", "transfer_type"], name="stock_trans_tenant__f9d4cd_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["tenant", "source_warehouse"], name="stock_trans_tenant__6139e4_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["tenant", "destination_warehouse"], name="stock_trans_tenant__9d07b0_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(fields=["tenant", "created_at"], name="stock_trans_tenant__be6a15_idx"),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "transfer_number"), name="stock_transfer_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransferhistory",
            index=models.Index(fields=["tenant", "stock_transfer"], name="stock_trans_tenant__bbf789_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferhistory",
            index=models.Index(fields=["tenant", "event_type"], name="stock_trans_tenant__426931_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferhistory",
            index=models.Index(fields=["tenant", "timestamp"], name="stock_trans_tenant__9397f0_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferline",
            index=models.Index(fields=["tenant", "stock_transfer"], name="stock_trans_tenant__b523e5_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferline",
            index=models.Index(fields=["tenant", "medicine"], name="stock_trans_tenant__c3b965_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferline",
            index=models.Index(fields=["tenant", "batch"], name="stock_trans_tenant__171547_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferdiscrepancy",
            index=models.Index(fields=["tenant", "stock_transfer"], name="stock_trans_tenant__641e71_idx"),
        ),
        migrations.AddIndex(
            model_name="stocktransferdiscrepancy",
            index=models.Index(fields=["tenant", "status"], name="stock_trans_tenant__61113e_idx"),
        ),
        migrations.AddConstraint(
            model_name="stocktransferdiscrepancy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "discrepancy_number"), name="stock_transfer_discrepancy_tenant_number_uniq"
            ),
        ),
    ]
