# Generated by Django 5.2.17 on 2026-08-09 00:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("suppliers", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("batch_number", models.CharField(db_index=True, max_length=100, verbose_name="Batch number")),
                ("lot_number", models.CharField(blank=True, default="", max_length=100, verbose_name="Lot number")),
                ("manufacturing_date", models.DateField(blank=True, null=True, verbose_name="Manufacturing date")),
                ("expiry_date", models.DateField(db_index=True, verbose_name="Expiry date")),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Regulatory registration number"
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Country of origin"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("quarantine", "Quarantine"),
                            ("expired", "Expired"),
                            ("recalled", "Recalled"),
                            ("blocked", "Blocked"),
                            ("depleted", "Depleted"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Batch status",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=0.0, max_digits=14, verbose_name="Purchase unit cost"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=4, default=0.0, max_digits=14, verbose_name="Suggested selling price"
                    ),
                ),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=14, verbose_name="Initial received quantity"
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=14, verbose_name="Current batch total quantity"
                    ),
                ),
                (
                    "storage_requirements",
                    models.TextField(blank=True, default="", verbose_name="Storage requirements"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch / Lot",
                "verbose_name_plural": "Batches / Lots",
                "ordering": ["expiry_date", "batch_number"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("quarantine", "Quarantine"),
                            ("damaged", "Damaged"),
                            ("expired", "Expired"),
                            ("blocked", "Blocked"),
                            ("recalled", "Recalled"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=30,
                        verbose_name="Inventory status",
                    ),
                ),
                (
                    "on_hand_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="On hand physical quantity",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Reserved quantity"
                    ),
                ),
                (
                    "damaged_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Damaged quantity"
                    ),
                ),
                (
                    "quarantine_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Quarantine quantity"
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Minimum stock limit"
                    ),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Maximum stock capacity"
                    ),
                ),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Reorder threshold point",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit cost"
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Weighted average cost",
                    ),
                ),
                (
                    "last_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Last purchase unit cost",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Current selling price",
                    ),
                ),
                (
                    "last_movement_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last stock movement date"),
                ),
                (
                    "last_count_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last physical count date"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["medicine__english_name", "batch__expiry_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("opening_balance", "Opening Balance"),
                            ("receipt", "Goods Receipt"),
                            ("sale", "POS / Sales Issue"),
                            ("sale_return", "Sales Return"),
                            ("purchase_return", "Purchase Return"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("adjustment_increase", "Stock Adjustment (+)"),
                            ("adjustment_decrease", "Stock Adjustment (-)"),
                            ("damage", "Damaged Stock"),
                            ("expiry", "Expired Stock"),
                            ("quarantine", "Placed in Quarantine"),
                            ("release_quarantine", "Released from Quarantine"),
                            ("reservation", "Stock Reservation"),
                            ("release_reservation", "Stock Reservation Release"),
                            ("correction", "System Correction"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Transaction type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Transaction quantity delta"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit cost"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Total transaction cost value",
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Stock on hand quantity before transaction"
                    ),
                ),
                (
                    "quantity_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Stock on hand quantity after transaction"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="External reference number"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opening_balance", "Opening Balance Load"),
                            ("correction", "Count Correction"),
                            ("damage", "Physical Damage"),
                            ("expiry", "Product Expiration"),
                            ("loss", "Shrinkage / Loss"),
                            ("found_stock", "Found Surplus Stock"),
                            ("system_correction", "System Data Fix"),
                            ("other", "Other Reason"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Adjustment / Reason code",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_transactions",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.inventoryitem",
                        verbose_name="Inventory Item",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who performed transaction",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_transactions",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["tenant", "status"], name="inventory_b_tenant__ab890c_idx"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["tenant", "medicine", "expiry_date"], name="inventory_b_tenant__69a14a_idx"),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(fields=["tenant", "expiry_date"], name="inventory_b_tenant__c4c360_idx"),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "medicine", "batch_number"), name="inventory_batch_tenant_med_batch_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["tenant", "warehouse", "medicine"], name="inventory_i_tenant__19c8f4_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["tenant", "medicine", "status"], name="inventory_i_tenant__64073a_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["warehouse", "storage_location"], name="inventory_i_warehou_b7c824_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(fields=["tenant", "status"], name="inventory_i_tenant__632f06_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.UniqueConstraint(
                fields=("tenant", "warehouse", "storage_location", "medicine", "batch"),
                name="inventory_item_wh_loc_med_batch_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand_quantity__gte", 0)), name="inventory_on_hand_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)), name="inventory_reserved_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("damaged_quantity__gte", 0)), name="inventory_damaged_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quarantine_quantity__gte", 0)), name="inventory_quarantine_non_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["tenant", "transaction_type"], name="inventory_i_tenant__5e6521_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["tenant", "medicine", "created_at"], name="inventory_i_tenant__332c61_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["tenant", "warehouse", "created_at"], name="inventory_i_tenant__240a7c_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(fields=["tenant", "batch"], name="inventory_i_tenant__1bf4bb_idx"),
        ),
    ]
