# Generated by Django 5.2.17 on 2026-08-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="inventory.batch",
                verbose_name="Batch",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("opening_balance", "Opening Balance"),
                    ("receipt", "Goods Receipt"),
                    ("issue", "Stock Issue"),
                    ("sale", "POS / Sales Issue"),
                    ("sale_return", "Sales Return"),
                    ("purchase_return", "Purchase Return"),
                    ("transfer_in", "Transfer In"),
                    ("transfer_out", "Transfer Out"),
                    ("adjustment", "Stock Adjustment"),
                    ("adjustment_increase", "Stock Adjustment (+)"),
                    ("adjustment_decrease", "Stock Adjustment (-)"),
                    ("damage", "Damaged Stock"),
                    ("expiry", "Expired Stock"),
                    ("quarantine", "Placed in Quarantine"),
                    ("release_quarantine", "Released from Quarantine"),
                    ("reservation", "Stock Reservation"),
                    ("release_reservation", "Stock Reservation Release"),
                    ("correction", "System Correction"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="Transaction type",
            ),
        ),
    ]
