# Generated by Django 5.2.17 on 2026-08-09 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventoryitem_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_transactions",
                to="inventory.batch",
                verbose_name="Batch",
            ),
        ),
    ]
