# Generated by Django 5.2.17 on 2026-08-11 00:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("goods_receipt", "0001_initial"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("procurement", "0001_initial"),
        ("purchase_returns", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountsPayableEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("payable_number", models.CharField(db_index=True, max_length=60, verbose_name="Payable Number (AP)")),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Original Payable Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Paid Amount"
                    ),
                ),
                (
                    "applied_credit_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Applied Credit Amount",
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Outstanding Balance"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="Due Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open Payable"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("written_off", "Written Off"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="AP Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_payable_entries",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_payable_entries",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts_payable_entries",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounts Payable Entry",
                "verbose_name_plural": "Accounts Payable Entries",
                "db_table": "accounts_payable_entries",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Internal Invoice Number (INV)"),
                ),
                (
                    "supplier_invoice_number",
                    models.CharField(db_index=True, max_length=100, verbose_name="Supplier Bill Number"),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("cash", "Cash on Delivery / Instant"),
                            ("net_7", "Net 7 Days"),
                            ("net_15", "Net 15 Days"),
                            ("net_30", "Net 30 Days"),
                            ("net_45", "Net 45 Days"),
                            ("net_60", "Net 60 Days"),
                            ("net_90", "Net 90 Days"),
                            ("custom", "Custom Due Date"),
                        ],
                        default="net_30",
                        max_length=20,
                        verbose_name="Payment Terms",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("received", "Received"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted to Accounts Payable"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("overdue", "Overdue"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("not_matched", "Not Matched"),
                            ("matched", "Matched (Three-Way Match OK)"),
                            ("partial_match", "Partial Match"),
                            ("price_variance", "Price Variance Identified"),
                            ("quantity_variance", "Quantity Variance Identified"),
                            ("tax_variance", "Tax Variance Identified"),
                            ("supplier_mismatch", "Supplier Mismatch"),
                            ("receipt_missing", "Goods Receipt Missing"),
                            ("disputed", "Disputed"),
                            ("approved", "Approved Match Exception"),
                        ],
                        db_index=True,
                        default="not_matched",
                        max_length=30,
                        verbose_name="Three-Way Match Status",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "shipping",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Shipping / Freight"
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Other Charges"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Grand Total"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Paid Amount"
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Outstanding Balance"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="Verified At")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_invoices",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="goods_receipt.goodsreceipt",
                        verbose_name="Goods Receipt",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="procurement.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_invoices",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_supplier_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Invoice",
                "verbose_name_plural": "Supplier Invoices",
                "db_table": "supplier_invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "dispute_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Dispute Number (DISP)"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("price_variance", "Price Variance vs PO"),
                            ("quantity_variance", "Quantity Variance vs Receipt"),
                            ("damaged_goods", "Damaged Goods Billed"),
                            ("missing_goods", "Missing / Shorted Goods Billed"),
                            ("wrong_item", "Wrong Product Invoiced"),
                            ("wrong_batch", "Wrong Batch Invoiced"),
                            ("tax_error", "Tax Rate / Tax Calculation Error"),
                            ("duplicate_invoice", "Duplicate Bill Invoiced"),
                            ("other", "Other Dispute Reason"),
                        ],
                        default="price_variance",
                        max_length=30,
                        verbose_name="Dispute Reason",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Disputed Amount"
                    ),
                ),
                ("evidence", models.TextField(blank=True, default="", verbose_name="Evidence / Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Under Review"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Dispute Status",
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="", verbose_name="Resolution Notes")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_disputes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_invoice_disputes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="accounts_payable.supplierinvoice",
                        verbose_name="Supplier Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Dispute",
                "verbose_name_plural": "Invoice Disputes",
                "db_table": "invoice_disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "applied_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Applied Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                ("applied_at", models.DateTimeField(auto_now_add=True, verbose_name="Applied At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "accounts_payable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_applications",
                        to="accounts_payable.accountspayableentry",
                        verbose_name="Accounts Payable Entry",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_supplier_credits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applied By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "supplier_credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="purchase_returns.suppliercreditnote",
                        verbose_name="Supplier Credit Note",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_applications",
                        to="accounts_payable.supplierinvoice",
                        verbose_name="Supplier Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Application",
                "verbose_name_plural": "Credit Applications",
                "db_table": "supplier_credit_applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddField(
            model_name="accountspayableentry",
            name="supplier_invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_payable_entry",
                to="accounts_payable.supplierinvoice",
                verbose_name="Supplier Invoice",
            ),
        ),
        migrations.CreateModel(
            name="SupplierInvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("description", models.CharField(max_length=255, verbose_name="Line Description")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Invoiced Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Price"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Subtotal"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Grand Total"
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Matched Received Quantity",
                    ),
                ),
                (
                    "invoiced_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Invoiced Quantity Copy",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoice_lines",
                        to="goods_receipt.goodsreceiptline",
                        verbose_name="Goods Receipt Line",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoice_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoice_lines",
                        to="procurement.purchaseorderline",
                        verbose_name="Purchase Order Line",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounts_payable.supplierinvoice",
                        verbose_name="Supplier Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Invoice Line",
                "verbose_name_plural": "Supplier Invoice Lines",
                "db_table": "supplier_invoice_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Payment Number (PAY)"),
                ),
                ("payment_date", models.DateField(verbose_name="Payment Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Payment Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Electronic Transfer / Wire"),
                            ("check", "Bank Check"),
                            ("card", "Corporate Credit / Debit Card"),
                            ("online_payment", "Online Payment Portal"),
                            ("other", "Other Payment Method"),
                        ],
                        default="bank_transfer",
                        max_length=30,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Reference / Check / Transaction ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted / Executed"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "accounts_payable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts_payable.accountspayableentry",
                        verbose_name="Accounts Payable Entry",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_payments",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_payments",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_supplier_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_payments",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts_payable.supplierinvoice",
                        verbose_name="Supplier Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment",
                "verbose_name_plural": "Supplier Payments",
                "db_table": "supplier_payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(fields=["tenant", "status"], name="supplier_in_tenant__c39dbe_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(fields=["tenant", "supplier"], name="supplier_in_tenant__b64f4a_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierinvoice",
            index=models.Index(fields=["tenant", "due_date"], name="supplier_in_tenant__3c20fe_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "supplier", "supplier_invoice_number"),
                name="supplier_invoice_tenant_supplier_bill_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"), name="supplier_invoice_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="accountspayableentry",
            index=models.Index(fields=["tenant", "status"], name="accounts_pa_tenant__c01b73_idx"),
        ),
        migrations.AddIndex(
            model_name="accountspayableentry",
            index=models.Index(fields=["tenant", "supplier"], name="accounts_pa_tenant__dc53b5_idx"),
        ),
        migrations.AddIndex(
            model_name="accountspayableentry",
            index=models.Index(fields=["tenant", "due_date"], name="accounts_pa_tenant__9e0e81_idx"),
        ),
        migrations.AddConstraint(
            model_name="accountspayableentry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "payable_number"), name="ap_entry_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(fields=["tenant", "status"], name="supplier_pa_tenant__0e3a6d_idx"),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(fields=["tenant", "supplier"], name="supplier_pa_tenant__5cc57d_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplierpayment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "payment_number"), name="supplier_payment_tenant_number_uniq"
            ),
        ),
    ]
