# Generated by Django 5.2.17 on 2026-08-12 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("general_ledger", "0001_initial"),
        ("sales", "0002_salesinvoiceline_returned_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("bank_name", models.CharField(max_length=150, verbose_name="Bank Name")),
                ("account_name", models.CharField(max_length=150, verbose_name="Bank Account Title / Holder")),
                ("account_number", models.CharField(db_index=True, max_length=50, verbose_name="Bank Account Number")),
                (
                    "masked_account_number",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Masked Display Number"),
                ),
                ("iban", models.CharField(blank=True, default="", max_length=60, verbose_name="IBAN Number")),
                (
                    "swift_bic",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="SWIFT / BIC Code"),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=20, verbose_name="Account Status"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Opening Ledger Balance",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Current Ledger Balance",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="branches.branch",
                        verbose_name="Branch Scope",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="general_ledger.chartofaccount",
                        verbose_name="Linked GL Chart of Account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "db_table": "bank_accounts",
                "ordering": ["bank_name", "account_number"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "reconciliation_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Reconciliation Code (REC)"),
                ),
                ("start_date", models.DateField(verbose_name="Statement Start Date")),
                ("end_date", models.DateField(verbose_name="Statement End Date")),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Opening Statement Balance",
                    ),
                ),
                (
                    "statement_closing_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Statement Closing Balance",
                    ),
                ),
                (
                    "book_closing_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Book Ledger Closing Balance",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Unreconciled Variance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Reconciliation"),
                            ("in_progress", "In Progress"),
                            ("reconciled", "Fully Reconciled"),
                            ("discrepancy", "Discrepancy Unresolved"),
                            ("closed", "Closed Period"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=25,
                        verbose_name="Reconciliation Status",
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True, verbose_name="Reconciled At")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bank_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="cash_and_bank.bankaccount",
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_reconciliations",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Reconciliation",
                "verbose_name_plural": "Bank Reconciliations",
                "db_table": "bank_reconciliations",
                "ordering": ["-end_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "transaction_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Transaction Number (BTX)"),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Bank External ID"
                    ),
                ),
                (
                    "import_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="Unique Import Hash Fingerprint"),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Transaction Date"
                    ),
                ),
                ("value_date", models.DateField(default=django.utils.timezone.now, verbose_name="Value Date")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Bank Deposit"),
                            ("withdrawal", "Bank Withdrawal"),
                            ("transfer", "Bank Transfer"),
                            ("fee", "Bank Fee / Charge"),
                            ("interest", "Interest Income / Expense"),
                            ("refund", "Bank Refund"),
                            ("payment", "Bank Payment"),
                            ("other", "Other Bank Transaction"),
                        ],
                        db_index=True,
                        default="deposit",
                        max_length=25,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Transaction Amount (+ Deposit, - Withdrawal)",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                ("reference", models.CharField(blank=True, default="", max_length=150, verbose_name="Bank Reference")),
                ("description", models.TextField(blank=True, default="", verbose_name="Transaction Description")),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("partially_matched", "Partially Matched"),
                            ("matched", "Matched"),
                            ("ignored", "Ignored / Excluded"),
                        ],
                        db_index=True,
                        default="unmatched",
                        max_length=25,
                        verbose_name="Reconciliation Status",
                    ),
                ),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Imported At")),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="cash_and_bank.bankaccount",
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Transaction",
                "verbose_name_plural": "Bank Transactions",
                "db_table": "bank_transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("name", models.CharField(max_length=150, verbose_name="Cash Account Name")),
                ("account_number", models.CharField(db_index=True, max_length=50, verbose_name="Cash Account Code")),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=20, verbose_name="Account Status"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Opening Float Balance",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Current Cash Balance"
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_accounts",
                        to="branches.branch",
                        verbose_name="Branch Scope",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_accounts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_accounts",
                        to="general_ledger.chartofaccount",
                        verbose_name="Linked GL Chart of Account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Account",
                "verbose_name_plural": "Cash Accounts",
                "db_table": "cash_accounts",
                "ordering": ["account_number"],
            },
        ),
        migrations.CreateModel(
            name="CashDeposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "deposit_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Deposit Number (DEP)"),
                ),
                ("deposit_date", models.DateField(default=django.utils.timezone.now, verbose_name="Deposit Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Deposit Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "reference",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Reference / Slip Number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="posted",
                        max_length=25,
                        verbose_name="Operation Status",
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_deposits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="cash_and_bank.bankaccount",
                        verbose_name="Destination Bank Account",
                    ),
                ),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="cash_and_bank.cashaccount",
                        verbose_name="Source Cash Account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_deposits",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Deposit",
                "verbose_name_plural": "Cash Deposits",
                "db_table": "cash_deposits",
                "ordering": ["-deposit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "movement_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Movement Number (CSM)"),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("sale", "POS Cash Sale"),
                            ("refund", "POS Cash Refund"),
                            ("customer_payment", "Customer AR Cash Payment"),
                            ("customer_receipt", "Customer Receipt"),
                            ("supplier_payment", "Supplier AP Cash Payment"),
                            ("deposit", "Cash Deposit to Bank"),
                            ("withdrawal", "Cash Withdrawal from Bank"),
                            ("transfer_in", "Cash Transfer In"),
                            ("transfer_out", "Cash Transfer Out"),
                            ("adjustment", "Cash Balance Adjustment"),
                            ("opening_balance", "Opening Float Balance"),
                            ("closing_adjustment", "Till Closing Variance Adjustment"),
                            ("other", "Other Cash Flow"),
                        ],
                        db_index=True,
                        default="sale",
                        max_length=35,
                        verbose_name="Movement Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Cash Movement Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50, verbose_name="Reference Type"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Reference ID"
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Movement Description")),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="cash_and_bank.cashaccount",
                        verbose_name="Cash Account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to="sales.registersession",
                        verbose_name="POS Register Session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Movement",
                "verbose_name_plural": "Cash Movements",
                "db_table": "cash_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "transfer_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Transfer Number (CTF)"),
                ),
                ("transfer_date", models.DateField(default=django.utils.timezone.now, verbose_name="Transfer Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Transfer Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                ("reference", models.CharField(blank=True, default="", max_length=100, verbose_name="Reference")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="posted",
                        max_length=25,
                        verbose_name="Operation Status",
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_transfers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "destination_cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="cash_and_bank.cashaccount",
                        verbose_name="Destination Cash Account",
                    ),
                ),
                (
                    "source_cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="cash_and_bank.cashaccount",
                        verbose_name="Source Cash Account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Transfer",
                "verbose_name_plural": "Cash Transfers",
                "db_table": "cash_transfers",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashVariance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "variance_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Variance Code (CVR)"),
                ),
                (
                    "variance_type",
                    models.CharField(
                        choices=[("shortage", "Cash Shortage (Deficit)"), ("overage", "Cash Overage (Surplus)")],
                        db_index=True,
                        default="shortage",
                        max_length=20,
                        verbose_name="Variance Type",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Expected Cash Amount"
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Actual Cash Counted"
                    ),
                ),
                (
                    "variance_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Variance Amount"
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="Cashier Reason / Explanation")),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Resolution Status (pending, approved, written_off)",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_variances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approving Manager",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variances",
                        to="sales.registersession",
                        verbose_name="POS Register Session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Variance",
                "verbose_name_plural": "Cash Variances",
                "db_table": "cash_variances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashWithdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "withdrawal_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Withdrawal Number (WTH)"),
                ),
                (
                    "withdrawal_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Withdrawal Date"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Withdrawal Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "purpose",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Withdrawal Purpose"),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100, verbose_name="Reference")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="posted",
                        max_length=25,
                        verbose_name="Operation Status",
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="cash_and_bank.bankaccount",
                        verbose_name="Source Bank Account",
                    ),
                ),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="cash_and_bank.cashaccount",
                        verbose_name="Destination Cash Account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_withdrawals",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Withdrawal",
                "verbose_name_plural": "Cash Withdrawals",
                "db_table": "cash_withdrawals",
                "ordering": ["-withdrawal_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("missing_book_entry", "Missing Book Entry"),
                            ("missing_external_entry", "Missing Bank Statement Entry"),
                            ("amount_mismatch", "Amount Mismatch"),
                            ("duplicate", "Duplicate Bank Transaction"),
                            ("unknown_transaction", "Unknown Transaction"),
                            ("timing_difference", "Timing Difference"),
                            ("bank_fee", "Unrecorded Bank Fee"),
                            ("interest", "Unrecorded Interest"),
                            ("fx_difference", "Exchange Rate Difference"),
                            ("other", "Other Discrepancy"),
                        ],
                        db_index=True,
                        default="missing_book_entry",
                        max_length=35,
                        verbose_name="Exception Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discrepancy Amount"
                    ),
                ),
                ("description", models.TextField(verbose_name="Exception Details")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open Exception"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Resolution Status",
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="", verbose_name="Resolution Notes")),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="cash_and_bank.banktransaction",
                        verbose_name="Bank Transaction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="cash_and_bank.bankreconciliation",
                        verbose_name="Reconciliation Session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Exception",
                "verbose_name_plural": "Reconciliation Exceptions",
                "db_table": "reconciliation_exceptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "matched_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Matched Amount"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Book Entry Type (e.g. CUSTOMER_PAYMENT, DEPOSIT)",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Book Entry Reference ID"),
                ),
                ("is_auto_matched", models.BooleanField(default=False, verbose_name="Auto-Matched by System")),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="cash_and_bank.banktransaction",
                        verbose_name="Bank Transaction",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="cash_and_bank.bankreconciliation",
                        verbose_name="Reconciliation Session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Match",
                "verbose_name_plural": "Reconciliation Matches",
                "db_table": "reconciliation_matches",
            },
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "account_number"), name="bank_acc_tenant_company_num_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankreconciliation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reconciliation_number"), name="brec_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(fields=["tenant", "reconciliation_status"], name="bank_transa_tenant__527277_idx"),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(fields=["tenant", "transaction_date"], name="bank_transa_tenant__d71a26_idx"),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("tenant", "bank_account", "import_hash"), name="btx_tenant_account_hash_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "account_number"), name="cash_acc_tenant_company_num_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashdeposit",
            constraint=models.UniqueConstraint(fields=("tenant", "deposit_number"), name="dep_tenant_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="cashmovement",
            constraint=models.UniqueConstraint(fields=("tenant", "movement_number"), name="csm_tenant_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="cashtransfer",
            constraint=models.UniqueConstraint(fields=("tenant", "transfer_number"), name="ctf_tenant_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="cashvariance",
            constraint=models.UniqueConstraint(fields=("tenant", "variance_number"), name="cvr_tenant_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="cashwithdrawal",
            constraint=models.UniqueConstraint(fields=("tenant", "withdrawal_number"), name="wth_tenant_number_uniq"),
        ),
    ]
