# Generated by Django 5.2.17 on 2026-08-14 07:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("rbac", "0002_seed_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("event_number", models.CharField(db_index=True, max_length=60, verbose_name="Event Number (EVT)")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.created", "User Created"),
                            ("user.locked", "User Account Locked"),
                            ("security.event", "Security Event"),
                            ("inventory.low_stock", "Medicine Low Stock"),
                            ("inventory.out_of_stock", "Medicine Out of Stock"),
                            ("inventory.near_expiry", "Medicine Near Expiry"),
                            ("inventory.expired", "Medicine Expired"),
                            ("inventory.batch_recalled", "Pharmaceutical Batch Recalled"),
                            ("inventory.stock_adjusted", "Stock Adjusted"),
                            ("inventory.stock_transferred", "Stock Transferred"),
                            ("procurement.purchase_created", "Purchase Order Created"),
                            ("goods_receipt.received", "Goods Receipt Received"),
                            ("accounts_payable.invoice_created", "Supplier Invoice Created"),
                            ("accounts_payable.payment_due", "Supplier Payment Due"),
                            ("sales.completed", "Sales Completed"),
                            ("sales.returned", "Sale Returned"),
                            ("sales.refund_created", "Refund Created"),
                            ("accounts_receivable.payment_overdue", "Customer Payment Overdue"),
                            ("prescription.created", "Prescription Created"),
                            ("prescription.verified", "Prescription Verified"),
                            ("prescription.dispensed", "Prescription Dispensed"),
                            ("cash.variance_detected", "Cash Shift Variance Detected"),
                            ("bank.reconciliation_difference", "Bank Reconciliation Difference"),
                            ("expenses.approval_required", "Expense Approval Required"),
                            ("expenses.approved", "Expense Approved"),
                            ("expenses.budget_threshold_reached", "Budget Threshold Reached"),
                            ("system.error", "System Error Alert"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                ("source_module", models.CharField(db_index=True, max_length=60, verbose_name="Source ERP Module")),
                ("source_object_id", models.CharField(db_index=True, max_length=100, verbose_name="Source Object ID")),
                ("payload", models.JSONField(default=dict, verbose_name="Event Data Payload")),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Occurred Timestamp"),
                ),
                (
                    "correlation_id",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Correlation ID"),
                ),
                (
                    "causation_id",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Causation ID"),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=120, verbose_name="Idempotency Key")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed Successfully"),
                            ("failed", "Processing Failed"),
                            ("dead_letter", "Moved to Dead Letter Queue"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Event Processing Status",
                    ),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="Retry Count")),
                ("last_error", models.TextField(blank=True, default="", verbose_name="Last Error Message")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor User",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domain_events",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_events",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Event",
                "verbose_name_plural": "Domain Events",
                "db_table": "notification_domain_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetterEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "dead_letter_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Dead Letter Number (DLE)"),
                ),
                ("failure_reason", models.TextField(verbose_name="Failure Reason / Traceback")),
                ("retry_count", models.IntegerField(default=0, verbose_name="Total Retries Attempted")),
                ("is_resolved", models.BooleanField(default=False, verbose_name="Is Resolved")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_dead_letters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By User",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dead_letter_records",
                        to="notifications.domainevent",
                        verbose_name="Domain Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dead Letter Event",
                "verbose_name_plural": "Dead Letter Events",
                "db_table": "notification_dead_letters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "notification_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Notification Number (NOT)"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Notification Title")),
                ("message", models.TextField(verbose_name="Notification Message")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email Notification"),
                            ("sms", "SMS Text Message"),
                            ("push", "Mobile/Browser Push"),
                            ("webhook", "Webhook HTTP POST"),
                            ("whatsapp", "WhatsApp Message"),
                        ],
                        db_index=True,
                        default="in_app",
                        max_length=20,
                        verbose_name="Delivery Channel",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                        verbose_name="Notification Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Delivery"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read by Recipient"),
                            ("failed", "Delivery Failed"),
                            ("dismissed", "Dismissed by Recipient"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Delivery Status",
                    ),
                ),
                ("action_url", models.CharField(blank=True, default="", max_length=500, verbose_name="Action URL")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata Payload")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="Read Timestamp")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Expiry Timestamp")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient User",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_notifications",
                        to="notifications.domainevent",
                        verbose_name="Source Event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email Notification"),
                            ("sms", "SMS Text Message"),
                            ("push", "Mobile/Browser Push"),
                            ("webhook", "Webhook HTTP POST"),
                            ("whatsapp", "WhatsApp Message"),
                        ],
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                ("provider_name", models.CharField(max_length=60, verbose_name="Provider Adapter Name")),
                ("attempt_number", models.IntegerField(default=1, verbose_name="Attempt Number")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Delivery"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read by Recipient"),
                            ("failed", "Delivery Failed"),
                            ("dismissed", "Dismissed by Recipient"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Attempt Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="External Provider Reference ID"
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Error Details")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery Log",
                "verbose_name_plural": "Notification Delivery Logs",
                "db_table": "notification_delivery_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.created", "User Created"),
                            ("user.locked", "User Account Locked"),
                            ("security.event", "Security Event"),
                            ("inventory.low_stock", "Medicine Low Stock"),
                            ("inventory.out_of_stock", "Medicine Out of Stock"),
                            ("inventory.near_expiry", "Medicine Near Expiry"),
                            ("inventory.expired", "Medicine Expired"),
                            ("inventory.batch_recalled", "Pharmaceutical Batch Recalled"),
                            ("inventory.stock_adjusted", "Stock Adjusted"),
                            ("inventory.stock_transferred", "Stock Transferred"),
                            ("procurement.purchase_created", "Purchase Order Created"),
                            ("goods_receipt.received", "Goods Receipt Received"),
                            ("accounts_payable.invoice_created", "Supplier Invoice Created"),
                            ("accounts_payable.payment_due", "Supplier Payment Due"),
                            ("sales.completed", "Sales Completed"),
                            ("sales.returned", "Sale Returned"),
                            ("sales.refund_created", "Refund Created"),
                            ("accounts_receivable.payment_overdue", "Customer Payment Overdue"),
                            ("prescription.created", "Prescription Created"),
                            ("prescription.verified", "Prescription Verified"),
                            ("prescription.dispensed", "Prescription Dispensed"),
                            ("cash.variance_detected", "Cash Shift Variance Detected"),
                            ("bank.reconciliation_difference", "Bank Reconciliation Difference"),
                            ("expenses.approval_required", "Expense Approval Required"),
                            ("expenses.approved", "Expense Approved"),
                            ("expenses.budget_threshold_reached", "Budget Threshold Reached"),
                            ("system.error", "System Error Alert"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email Notification"),
                            ("sms", "SMS Text Message"),
                            ("push", "Mobile/Browser Push"),
                            ("webhook", "Webhook HTTP POST"),
                            ("whatsapp", "WhatsApp Message"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Is Channel Enabled")),
                ("quiet_hours_start", models.TimeField(blank=True, null=True, verbose_name="Quiet Hours Start Time")),
                ("quiet_hours_end", models.TimeField(blank=True, null=True, verbose_name="Quiet Hours End Time")),
                (
                    "minimum_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Minimum Priority Threshold",
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate Delivery"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest Summary"),
                            ("weekly", "Weekly Digest Summary"),
                        ],
                        default="immediate",
                        max_length=20,
                        verbose_name="Digest Frequency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, verbose_name="Template Code")),
                ("name", models.CharField(max_length=150, verbose_name="Template Name")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.created", "User Created"),
                            ("user.locked", "User Account Locked"),
                            ("security.event", "Security Event"),
                            ("inventory.low_stock", "Medicine Low Stock"),
                            ("inventory.out_of_stock", "Medicine Out of Stock"),
                            ("inventory.near_expiry", "Medicine Near Expiry"),
                            ("inventory.expired", "Medicine Expired"),
                            ("inventory.batch_recalled", "Pharmaceutical Batch Recalled"),
                            ("inventory.stock_adjusted", "Stock Adjusted"),
                            ("inventory.stock_transferred", "Stock Transferred"),
                            ("procurement.purchase_created", "Purchase Order Created"),
                            ("goods_receipt.received", "Goods Receipt Received"),
                            ("accounts_payable.invoice_created", "Supplier Invoice Created"),
                            ("accounts_payable.payment_due", "Supplier Payment Due"),
                            ("sales.completed", "Sales Completed"),
                            ("sales.returned", "Sale Returned"),
                            ("sales.refund_created", "Refund Created"),
                            ("accounts_receivable.payment_overdue", "Customer Payment Overdue"),
                            ("prescription.created", "Prescription Created"),
                            ("prescription.verified", "Prescription Verified"),
                            ("prescription.dispensed", "Prescription Dispensed"),
                            ("cash.variance_detected", "Cash Shift Variance Detected"),
                            ("bank.reconciliation_difference", "Bank Reconciliation Difference"),
                            ("expenses.approval_required", "Expense Approval Required"),
                            ("expenses.approved", "Expense Approved"),
                            ("expenses.budget_threshold_reached", "Budget Threshold Reached"),
                            ("system.error", "System Error Alert"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Target Event Type",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email Notification"),
                            ("sms", "SMS Text Message"),
                            ("push", "Mobile/Browser Push"),
                            ("webhook", "Webhook HTTP POST"),
                            ("whatsapp", "WhatsApp Message"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Delivery Channel",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name="Language Code (e.g. 'en', 'ar')"),
                ),
                (
                    "subject_template",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Subject Template"),
                ),
                ("body_template", models.TextField(verbose_name="Body Template Text")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, verbose_name="Rule Code")),
                ("name", models.CharField(max_length=150, verbose_name="Rule Name")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.created", "User Created"),
                            ("user.locked", "User Account Locked"),
                            ("security.event", "Security Event"),
                            ("inventory.low_stock", "Medicine Low Stock"),
                            ("inventory.out_of_stock", "Medicine Out of Stock"),
                            ("inventory.near_expiry", "Medicine Near Expiry"),
                            ("inventory.expired", "Medicine Expired"),
                            ("inventory.batch_recalled", "Pharmaceutical Batch Recalled"),
                            ("inventory.stock_adjusted", "Stock Adjusted"),
                            ("inventory.stock_transferred", "Stock Transferred"),
                            ("procurement.purchase_created", "Purchase Order Created"),
                            ("goods_receipt.received", "Goods Receipt Received"),
                            ("accounts_payable.invoice_created", "Supplier Invoice Created"),
                            ("accounts_payable.payment_due", "Supplier Payment Due"),
                            ("sales.completed", "Sales Completed"),
                            ("sales.returned", "Sale Returned"),
                            ("sales.refund_created", "Refund Created"),
                            ("accounts_receivable.payment_overdue", "Customer Payment Overdue"),
                            ("prescription.created", "Prescription Created"),
                            ("prescription.verified", "Prescription Verified"),
                            ("prescription.dispensed", "Prescription Dispensed"),
                            ("cash.variance_detected", "Cash Shift Variance Detected"),
                            ("bank.reconciliation_difference", "Bank Reconciliation Difference"),
                            ("expenses.approval_required", "Expense Approval Required"),
                            ("expenses.approved", "Expense Approved"),
                            ("expenses.budget_threshold_reached", "Budget Threshold Reached"),
                            ("system.error", "System Error Alert"),
                        ],
                        db_index=True,
                        max_length=100,
                        verbose_name="Triggering Event Type",
                    ),
                ),
                (
                    "condition_json",
                    models.JSONField(blank=True, default=dict, verbose_name="Condition Expression JSON"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email Notification"),
                            ("sms", "SMS Text Message"),
                            ("push", "Mobile/Browser Push"),
                            ("webhook", "Webhook HTTP POST"),
                            ("whatsapp", "WhatsApp Message"),
                        ],
                        default="in_app",
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active Rule")),
                (
                    "cooldown_minutes",
                    models.IntegerField(default=15, verbose_name="Alert Deduplication Cooldown Minutes"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_rules",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_rules",
                        to="rbac.role",
                        verbose_name="Target RBAC Role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_rules",
                        to="notifications.notificationtemplate",
                        verbose_name="Notification Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Rule",
                "verbose_name_plural": "Notification Rules",
                "db_table": "notification_rules",
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("processed", "Processed Successfully"),
                            ("failed", "Processing Failed"),
                            ("dead_letter", "Moved to Dead Letter Queue"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Outbox Status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Scheduled Processing Time"),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="Processed At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "domain_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_record",
                        to="notifications.domainevent",
                        verbose_name="Domain Event",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbox Event",
                "verbose_name_plural": "Outbox Events",
                "db_table": "notification_outbox_events",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("name", models.CharField(max_length=150, verbose_name="Webhook Name")),
                ("target_url", models.URLField(max_length=500, verbose_name="Target HTTP URL")),
                ("secret", models.CharField(max_length=128, verbose_name="HMAC Signing Secret")),
                ("subscribed_events", models.JSONField(default=list, verbose_name="Subscribed Event Types")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "last_delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last Successful Delivery"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "db_table": "notification_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="domainevent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="evt_tenant_idempotency_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "event_type", "channel"), name="pref_user_event_channel_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationtemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "language"), name="tmpl_tenant_code_lang_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationrule",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="rule_tenant_code_uniq"),
        ),
    ]
