# Generated by Django 5.2.17 on 2026-08-10 23:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("rule_name", models.CharField(max_length=150, verbose_name="Rule Name")),
                (
                    "expiry_days_threshold_near",
                    models.PositiveIntegerField(default=90, verbose_name="Near Expiry Warning Days"),
                ),
                (
                    "expiry_days_threshold_critical",
                    models.PositiveIntegerField(default=30, verbose_name="Critical Expiry Warning Days"),
                ),
                (
                    "reorder_point_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=6,
                        verbose_name="Reorder Point Alert Trigger Ratio (%)",
                    ),
                ),
                (
                    "enable_auto_quarantine_on_recall",
                    models.BooleanField(default=True, verbose_name="Enable Auto Quarantine on Recall"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Is Active")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_configurations",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_configurations",
                        to="medicines.medicine",
                        verbose_name="Medicine Scope",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_configurations",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse Scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Configuration",
                "verbose_name_plural": "Alert Configurations",
                "db_table": "alert_configurations",
                "ordering": ["rule_name"],
                "indexes": [models.Index(fields=["tenant", "is_active"], name="alert_confi_tenant__63e962_idx")],
            },
        ),
        migrations.CreateModel(
            name="BatchRecall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("recall_number", models.CharField(db_index=True, max_length=60, verbose_name="Recall Order Number")),
                (
                    "recall_type",
                    models.CharField(
                        choices=[
                            ("voluntary_manufacturer", "Voluntary Manufacturer Recall"),
                            ("regulatory_fda", "FDA Regulatory Order"),
                            ("sfda_directive", "SFDA Regulatory Directive"),
                            ("quality_defect", "Quality Defect Investigation"),
                            ("safety_warning", "Safety Warning & Withdrawal"),
                        ],
                        default="voluntary_manufacturer",
                        max_length=40,
                        verbose_name="Recall Type",
                    ),
                ),
                (
                    "recall_class",
                    models.CharField(
                        choices=[
                            ("class_1", "Class I (High Risk of Severe Adverse Health Consequences)"),
                            ("class_2", "Class II (Temporary or Medically Reversible Health Risk)"),
                            ("class_3", "Class III (Unlikely to Cause Adverse Health Consequences)"),
                        ],
                        default="class_2",
                        max_length=20,
                        verbose_name="Recall Class",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Recall"),
                            ("initiated", "Recall Initiated"),
                            ("quarantine_in_progress", "Stock Quarantining In Progress"),
                            ("quarantined", "Stock Fully Quarantined"),
                            ("completed", "Recall Completed & Closed"),
                            ("cancelled", "Recall Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Recall Status",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for Recall")),
                ("action_required", models.TextField(blank=True, default="", verbose_name="Action Required")),
                (
                    "regulatory_reference",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Regulatory Reference / Notice No."
                    ),
                ),
                (
                    "quarantined_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Quarantined Quantity"
                    ),
                ),
                (
                    "disposed_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Disposed Quantity"
                    ),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Returned Quantity"
                    ),
                ),
                ("initiated_at", models.DateTimeField(blank=True, null=True, verbose_name="Initiated At")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed At")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recalls",
                        to="inventory.batch",
                        verbose_name="Recalled Batch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_recalls",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_recalls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_recalls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Initiated By",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_recalls",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Recall",
                "verbose_name_plural": "Batch Recalls",
                "db_table": "batch_recalls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="batch_recal_tenant__d6bd4d_idx"),
                    models.Index(fields=["tenant", "batch"], name="batch_recal_tenant__df5bfa_idx"),
                    models.Index(fields=["tenant", "medicine"], name="batch_recal_tenant__faabee_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "recall_number"), name="batch_recall_tenant_number_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("alert_number", models.CharField(db_index=True, max_length=60, verbose_name="Alert Number")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock Warning"),
                            ("reorder_point", "Reorder Point Reached"),
                            ("out_of_stock", "Out of Stock Critical"),
                            ("overstock", "Overstock Alert"),
                            ("expiry_warning", "Near Expiry Warning"),
                            ("expired", "Stock Expired Critical"),
                            ("batch_recall", "Batch Recall Notice"),
                            ("quarantine_notice", "Quarantine Notice"),
                            ("temperature_excursion", "Temperature Excursion"),
                            ("custom", "Custom Operational Alert"),
                        ],
                        db_index=True,
                        default="low_stock",
                        max_length=40,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low Severity"),
                            ("medium", "Medium Severity"),
                            ("high", "High Severity"),
                            ("critical", "Critical Action Required"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Alert"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "Resolution In Progress"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("suppressed", "Suppressed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Alert Status",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Current Value"
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Threshold Value"
                    ),
                ),
                ("triggered_at", models.DateTimeField(db_index=True, verbose_name="Triggered At")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True, verbose_name="Acknowledged At")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                ("resolution_notes", models.TextField(blank=True, default="", verbose_name="Resolution Notes")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acknowledged By",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_alerts",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_alerts",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_alerts",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Alert",
                "verbose_name_plural": "Inventory Alerts",
                "db_table": "inventory_alerts",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="inventory_a_tenant__ae8053_idx"),
                    models.Index(fields=["tenant", "severity"], name="inventory_a_tenant__1d40b8_idx"),
                    models.Index(fields=["tenant", "alert_type"], name="inventory_a_tenant__d934ab_idx"),
                    models.Index(fields=["tenant", "medicine"], name="inventory_a_tenant__7d9860_idx"),
                    models.Index(fields=["tenant", "triggered_at"], name="inventory_a_tenant__94a520_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "alert_number"), name="inventory_alert_tenant_number_uniq"
                    )
                ],
            },
        ),
    ]
