# Generated by Django 5.2.17 on 2026-08-07 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "employee_number",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Employee number"),
                ),
                ("arabic_name", models.CharField(blank=True, default="", max_length=200, verbose_name="Arabic name")),
                (
                    "english_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="English name"),
                ),
                ("national_id", models.CharField(blank=True, default="", max_length=50, verbose_name="National ID")),
                (
                    "passport_number",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Passport number"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        default="",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="Date of birth")),
                ("job_title", models.CharField(blank=True, default="", max_length=100, verbose_name="Job title")),
                ("department", models.CharField(blank=True, default="", max_length=100, verbose_name="Department")),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("intern", "Intern"),
                            ("temporary", "Temporary"),
                        ],
                        default="full_time",
                        max_length=30,
                        verbose_name="Employment type",
                    ),
                ),
                ("position", models.CharField(blank=True, default="", max_length=100, verbose_name="Position")),
                ("job_grade", models.CharField(blank=True, default="", max_length=50, verbose_name="Job grade")),
                ("hire_date", models.DateField(blank=True, null=True, verbose_name="Hire date")),
                ("termination_date", models.DateField(blank=True, null=True, verbose_name="Termination date")),
                ("emergency_contact", models.JSONField(blank=True, default=dict, verbose_name="Emergency contact")),
                ("mfa_enabled", models.BooleanField(default=False, verbose_name="MFA enabled")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="employee_profiles",
                        to="branches.branch",
                        verbose_name="Assigned branches",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profiles",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "direct_supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_employees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Direct supervisor",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Manager",
                    ),
                ),
                (
                    "primary_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_employee_profiles",
                        to="branches.branch",
                        verbose_name="Primary branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Profile",
                "verbose_name_plural": "Employee Profiles",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("employee_number__gt", "")),
                        fields=("tenant", "employee_number"),
                        name="users_emp_profile_tenant_emp_num_uniq",
                    )
                ],
            },
        ),
    ]
