# Generated by Django 5.2.17 on 2026-08-09 01:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("count_number", models.CharField(db_index=True, max_length=100, verbose_name="Count Number")),
                (
                    "count_type",
                    models.CharField(
                        choices=[
                            ("full_count", "Full Stock Count"),
                            ("partial_count", "Partial Stock Count"),
                            ("cycle_count", "Cycle Count"),
                            ("spot_count", "Spot Check Count"),
                            ("recount", "Recount Session"),
                            ("blind_count", "Blind Stock Count"),
                            ("batch_count", "Batch-Specific Count"),
                            ("location_count", "Location-Specific Count"),
                            ("warehouse_count", "Warehouse-Wide Count"),
                        ],
                        db_index=True,
                        default="warehouse_count",
                        max_length=50,
                        verbose_name="Count Type",
                    ),
                ),
                (
                    "count_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted for Review"),
                            ("under_review", "Under Review"),
                            ("recount_required", "Recount Required"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("reconciled", "Reconciled & Adjusted"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=50,
                        verbose_name="Count Status",
                    ),
                ),
                (
                    "count_scope_type",
                    models.CharField(
                        choices=[
                            ("tenant", "Tenant-Wide"),
                            ("company", "Company-Wide"),
                            ("branch", "Branch-Wide"),
                            ("warehouse", "Warehouse-Wide"),
                            ("location", "Storage Location"),
                            ("medicine", "Medicine Master"),
                            ("medicine_category", "Medicine Category"),
                            ("batch", "Specific Batch"),
                            ("custom_set", "Custom Selected Set"),
                        ],
                        default="warehouse",
                        max_length=50,
                        verbose_name="Count Scope Type",
                    ),
                ),
                (
                    "scope_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explicit parameters defining the count scope filter.",
                        verbose_name="Scope Filter Parameters",
                    ),
                ),
                (
                    "is_blind_count",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When true, physical counters cannot view system quantities during counting.",
                        verbose_name="Is Blind Count",
                    ),
                ),
                (
                    "freeze_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="When true, stock movements on the specified scope are locked while count is active.",
                        verbose_name="Freeze Inventory",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(blank=True, null=True, verbose_name="Snapshot Timestamp")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Started Timestamp")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="Submitted Timestamp")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Reviewed Timestamp")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved Timestamp")),
                ("reconciled_at", models.DateTimeField(blank=True, null=True, verbose_name="Reconciled Timestamp")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled Timestamp")),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Reason")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("total_items_counted", models.IntegerField(default=0, verbose_name="Total Items Counted")),
                (
                    "total_shortage_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Total Shortage Quantity",
                    ),
                ),
                (
                    "total_overage_quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Total Overage Quantity"
                    ),
                ),
                (
                    "total_variance_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Variance Cost"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=100, verbose_name="Idempotency Key"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_counts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Completed By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reconciled By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Started By",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_counts",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Count",
                "verbose_name_plural": "Stock Counts",
                "db_table": "stock_count",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("event_type", models.CharField(db_index=True, max_length=100, verbose_name="Audit Event Type")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Event Details")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Event Timestamp")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_count_history_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By User",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock_adjustment.stockcount",
                        verbose_name="Stock Count Document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Count History Event",
                "verbose_name_plural": "Stock Count History Events",
                "db_table": "stock_count_history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "snapshot_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="System on-hand quantity captured at snapshot time.",
                        max_digits=14,
                        verbose_name="System Snapshot Quantity",
                    ),
                ),
                (
                    "counted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Physically Counted Quantity",
                    ),
                ),
                (
                    "variance_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="counted_quantity - snapshot_quantity",
                        max_digits=14,
                        verbose_name="Variance Quantity",
                    ),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7, verbose_name="Variance Percentage"
                    ),
                ),
                (
                    "variance_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="variance_quantity * unit_cost",
                        max_digits=14,
                        verbose_name="Variance Cost",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Unit Cost at Snapshot",
                    ),
                ),
                (
                    "variance_direction",
                    models.CharField(
                        choices=[
                            ("shortage", "Shortage (-)"),
                            ("overage", "Overage (+)"),
                            ("no_variance", "No Variance (Exact Match)"),
                        ],
                        db_index=True,
                        default="no_variance",
                        max_length=20,
                        verbose_name="Variance Direction",
                    ),
                ),
                ("requires_recount", models.BooleanField(default=False, verbose_name="Requires Recount")),
                ("recount_reason", models.CharField(blank=True, max_length=255, verbose_name="Recount Reason")),
                ("notes", models.TextField(blank=True, verbose_name="Line Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_count_lines",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_count_line_counts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Counted By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_count_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock_adjustment.stockcount",
                        verbose_name="Stock Count Document",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_count_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Count Line",
                "verbose_name_plural": "Stock Count Lines",
                "db_table": "stock_count_line",
                "ordering": ["stock_count", "medicine"],
            },
        ),
        migrations.CreateModel(
            name="StockCountRecount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("recount_number", models.CharField(db_index=True, max_length=100, verbose_name="Recount Number")),
                (
                    "recount_status",
                    models.CharField(
                        choices=[
                            ("pending", "Recount Pending"),
                            ("requested", "Recount Requested"),
                            ("in_progress", "Recount In Progress"),
                            ("completed", "Recount Completed"),
                            ("approved", "Recount Approved"),
                            ("rejected", "Recount Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Recount Status",
                    ),
                ),
                (
                    "original_counted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Original Counted Quantity",
                    ),
                ),
                (
                    "recount_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Recount Quantity"
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, verbose_name="Recount Reason")),
                ("notes", models.TextField(blank=True, verbose_name="Recount Notes")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Recount Completed At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "recounted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_recounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recounted By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_recounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recounts",
                        to="stock_adjustment.stockcount",
                        verbose_name="Stock Count Document",
                    ),
                ),
                (
                    "stock_count_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recount_history",
                        to="stock_adjustment.stockcountline",
                        verbose_name="Stock Count Line",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Count Recount",
                "verbose_name_plural": "Stock Count Recounts",
                "db_table": "stock_count_recount",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("session_number", models.CharField(db_index=True, max_length=100, verbose_name="Session Number")),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Session"),
                            ("active", "Active Session"),
                            ("completed", "Completed Session"),
                            ("cancelled", "Cancelled Session"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Session Status",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Session Started At")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Session Completed At")),
                ("notes", models.TextField(blank=True, verbose_name="Session Notes")),
                (
                    "assigned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned Counter User",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="stock_adjustment.stockcount",
                        verbose_name="Stock Count Document",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="count_sessions",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_sessions",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Count Session",
                "verbose_name_plural": "Stock Count Sessions",
                "db_table": "stock_count_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(fields=["tenant", "count_status"], name="stock_count_tenant__597f12_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(fields=["tenant", "count_type"], name="stock_count_tenant__4ec911_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(fields=["tenant", "created_at"], name="stock_count_tenant__7b5e61_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "count_number"), name="stock_count_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="stockcounthistory",
            index=models.Index(fields=["tenant", "stock_count"], name="stock_count_tenant__aa434e_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcounthistory",
            index=models.Index(fields=["tenant", "event_type"], name="stock_count_tenant__a37daf_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcounthistory",
            index=models.Index(fields=["tenant", "timestamp"], name="stock_count_tenant__9e3dea_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(fields=["tenant", "stock_count"], name="stock_count_tenant__ea697b_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(fields=["tenant", "medicine"], name="stock_count_tenant__4d13c6_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(fields=["tenant", "variance_direction"], name="stock_count_tenant__efbe5c_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountrecount",
            index=models.Index(fields=["tenant", "stock_count"], name="stock_count_tenant__a6b426_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountrecount",
            index=models.Index(fields=["tenant", "recount_status"], name="stock_count_tenant__ace739_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountsession",
            index=models.Index(fields=["tenant", "stock_count"], name="stock_count_tenant__f3fa83_idx"),
        ),
        migrations.AddIndex(
            model_name="stockcountsession",
            index=models.Index(fields=["tenant", "session_status"], name="stock_count_tenant__9ff782_idx"),
        ),
    ]
