# Generated by Django 5.2.17 on 2026-08-14 22:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "feature_key",
                    models.CharField(db_index=True, max_length=100, unique=True, verbose_name="Feature Key"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Feature Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Feature Description")),
                ("is_globally_enabled", models.BooleanField(default=False, verbose_name="Is Globally Enabled")),
                ("rollout_percentage", models.IntegerField(default=0, verbose_name="Rollout Percentage (0-100)")),
                (
                    "target_tiers",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Target Subscription Tiers (e.g. ['enterprise'])"
                    ),
                ),
                (
                    "whitelisted_tenants",
                    models.JSONField(blank=True, default=list, verbose_name="Whitelisted Tenant Slugs/Codes"),
                ),
                (
                    "blacklisted_tenants",
                    models.JSONField(blank=True, default=list, verbose_name="Blacklisted Tenant Slugs/Codes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Feature Flag",
                "verbose_name_plural": "Global Feature Flags",
                "db_table": "platform_feature_flags",
            },
        ),
        migrations.CreateModel(
            name="PlatformAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical Outage / Security"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=20,
                        verbose_name="Alert Severity",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security & Authentication"),
                            ("billing", "Subscription & Billing"),
                            ("performance", "System Performance & Latency"),
                            ("infrastructure", "Database, Redis & Celery"),
                            ("compliance", "Compliance & Regulatory"),
                        ],
                        db_index=True,
                        default="infrastructure",
                        max_length=30,
                        verbose_name="Alert Category",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Alert Title")),
                ("message", models.TextField(verbose_name="Alert Message")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Diagnostic Metadata")),
                ("is_resolved", models.BooleanField(db_index=True, default=False, verbose_name="Is Resolved")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved Timestamp")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_platform_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By Admin",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Alert",
                "verbose_name_plural": "Platform Alerts",
                "db_table": "platform_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("action", models.CharField(db_index=True, max_length=100, verbose_name="Action Code")),
                (
                    "target_object_type",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="Target Object Type"),
                ),
                (
                    "target_object_id",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="Target Object ID"),
                ),
                ("description", models.TextField(verbose_name="Action Description")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Change Delta Payload")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address")),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="Timestamp"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Admin Actor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "target_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audits",
                        to="core.tenant",
                        verbose_name="Target Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Audit Log",
                "verbose_name_plural": "Platform Audit Logs",
                "db_table": "platform_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("component_name", models.CharField(db_index=True, max_length=60, verbose_name="Component Name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded Performance"),
                            ("down", "Service Down / Outage"),
                        ],
                        db_index=True,
                        default="healthy",
                        max_length=20,
                        verbose_name="Health Status",
                    ),
                ),
                ("latency_ms", models.FloatField(default=0.0, verbose_name="Response Latency (ms)")),
                (
                    "checked_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Checked Timestamp"
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Diagnostic Metadata Details")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Error Details")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "db_table": "platform_health_checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemMaintenanceWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("title", models.CharField(max_length=150, verbose_name="Maintenance Title")),
                ("description", models.TextField(blank=True, default="", verbose_name="Maintenance Description")),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Maintenance Window Active")),
                (
                    "bypass_key",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Emergency Bypass Key"),
                ),
                (
                    "affected_services",
                    models.JSONField(blank=True, default=list, verbose_name="Affected Services List"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Maintenance Window",
                "verbose_name_plural": "System Maintenance Windows",
                "db_table": "platform_maintenance_windows",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TenantImpersonationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("reason", models.TextField(verbose_name="Impersonation Justification Reason")),
                (
                    "ticket_reference",
                    models.CharField(blank=True, default="", max_length=60, verbose_name="Support Ticket ID"),
                ),
                (
                    "started_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Session Started At"),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True, verbose_name="Session Ended At")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="Client IP Address")),
                ("actions_count", models.IntegerField(default=0, verbose_name="Actions Performed Count")),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Super Admin User",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "impersonated_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impersonated_logs",
                        to="core.tenant",
                        verbose_name="Impersonated Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Impersonation Log",
                "verbose_name_plural": "Tenant Impersonation Logs",
                "db_table": "platform_impersonation_logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
