# Generated by Django 5.2.17 on 2026-08-11 00:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("procurement", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "receipt_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Receipt Number (GRN)"),
                ),
                (
                    "supplier_delivery_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Supplier Delivery Note No."
                    ),
                ),
                (
                    "supplier_invoice_reference",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Supplier Invoice Reference"
                    ),
                ),
                ("receipt_date", models.DateField(verbose_name="Receipt Date")),
                ("delivery_date", models.DateField(blank=True, null=True, verbose_name="Supplier Delivery Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("receiving", "Receiving in Progress"),
                            ("pending_verification", "Pending Inspection & Verification"),
                            ("pending_approval", "Pending Approval"),
                            ("partially_received", "Partially Received"),
                            ("completed", "Completed & Posted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Receipt Status",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Shipping Cost"
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Other Charges"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Grand Total"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_receipts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to="procurement.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Received By",
                    ),
                ),
                (
                    "receiving_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipts",
                        to="warehouses.storagelocation",
                        verbose_name="Default Receiving Location",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_goods_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipts",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt",
                "verbose_name_plural": "Goods Receipts",
                "db_table": "goods_receipts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("batch_number", models.CharField(db_index=True, max_length=100, verbose_name="Batch Number")),
                ("manufacturing_date", models.DateField(blank=True, null=True, verbose_name="Manufacturing Date")),
                ("expiry_date", models.DateField(db_index=True, verbose_name="Expiry Date")),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=14,
                        verbose_name="Total Received Quantity",
                    ),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Accepted Quantity"
                    ),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Rejected Quantity"
                    ),
                ),
                (
                    "damaged_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Damaged Quantity"
                    ),
                ),
                (
                    "free_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Free Quantity Received",
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Purchase Unit Cost"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Tax"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Line Cost"
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted - Quality Verified"),
                            ("rejected", "Rejected - Failed Inspection"),
                            ("quarantined", "Quarantined for Inspection"),
                            ("damaged", "Damaged Goods"),
                            ("pending_inspection", "Pending Inspection"),
                            ("expired", "Expired Stock"),
                            ("recalled", "Recalled Batch"),
                        ],
                        db_index=True,
                        default="accepted",
                        max_length=30,
                        verbose_name="Quality Inspection Status",
                    ),
                ),
                (
                    "temperature_at_receipt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Temperature At Receipt (°C)",
                    ),
                ),
                (
                    "min_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Min Allowed Temperature (°C)",
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Max Allowed Temperature (°C)",
                    ),
                ),
                (
                    "temperature_excursion_flag",
                    models.BooleanField(default=False, verbose_name="Temperature Excursion Flag"),
                ),
                ("inspection_result", models.TextField(blank=True, default="", verbose_name="Inspection Notes")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipt_lines",
                        to="inventory.batch",
                        verbose_name="Created / Reused Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="goods_receipt.goodsreceipt",
                        verbose_name="Goods Receipt",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goods_receipt_lines",
                        to="procurement.purchaseorderline",
                        verbose_name="Purchase Order Line",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goods_receipt_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Destination Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goods Receipt Line",
                "verbose_name_plural": "Goods Receipt Lines",
                "db_table": "goods_receipt_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(fields=["tenant", "status"], name="goods_recei_tenant__915fb3_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(fields=["tenant", "supplier"], name="goods_recei_tenant__834530_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(fields=["tenant", "purchase_order"], name="goods_recei_tenant__5fdaf4_idx"),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(fields=["tenant", "warehouse"], name="goods_recei_tenant__427ea5_idx"),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                fields=("tenant", "receipt_number"), name="goods_receipt_tenant_number_uniq"
            ),
        ),
    ]
