# Generated by Django 5.2.17 on 2026-08-05 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "refresh_token_jti",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Refresh token JTI"),
                ),
                ("device_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Device name")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("api", "API"),
                        ],
                        default="web",
                        max_length=24,
                        verbose_name="Device type",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User agent")),
                ("remember_me", models.BooleanField(default=False, verbose_name="Remember me")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="Last used at")),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Expires at")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="Revoked at")),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "User logged out"),
                            ("security", "Revoked for security reasons"),
                            ("password_change", "Password was changed"),
                            ("admin", "Revoked by an administrator"),
                            ("expired", "Session expired"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Revoke reason",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revoked by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login session",
                "verbose_name_plural": "Login sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("password_hash", models.CharField(max_length=255, verbose_name="Password hash")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password history entry",
                "verbose_name_plural": "Password history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("registered", "Account registered"),
                            ("login_success", "Login succeeded"),
                            ("login_failed", "Login failed"),
                            ("login_locked", "Account locked after failed logins"),
                            ("logout", "Logged out"),
                            ("token_refreshed", "Token refreshed"),
                            ("email_verification_requested", "Email verification requested"),
                            ("email_verified", "Email verified"),
                            ("phone_verification_requested", "Phone verification requested"),
                            ("phone_verified", "Phone verified"),
                            ("password_reset_requested", "Password reset requested"),
                            ("password_reset_confirmed", "Password reset confirmed"),
                            ("password_changed", "Password changed"),
                            ("session_revoked", "Session revoked"),
                            ("account_locked", "Account locked"),
                            ("account_unlocked", "Account unlocked"),
                            ("account_deactivated", "Account deactivated"),
                            ("account_activated", "Account activated"),
                            ("profile_updated", "Profile updated"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Event type",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User agent")),
                ("device_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Device name")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Details")),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to="authentication.loginsession",
                        verbose_name="Session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security event",
                "verbose_name_plural": "Security events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email verification"),
                            ("phone_verification", "Phone verification"),
                            ("password_reset", "Password reset"),
                            ("email_change", "Email change"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Kind",
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True, verbose_name="Token hash")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="Expires at")),
                ("consumed_at", models.DateTimeField(blank=True, null=True, verbose_name="Consumed at")),
                ("attempts", models.PositiveSmallIntegerField(default=0, verbose_name="Failed attempts")),
                ("max_attempts", models.PositiveSmallIntegerField(default=5, verbose_name="Max attempts")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification token",
                "verbose_name_plural": "Verification tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(fields=["user", "is_active"], name="auth_session_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(fields=["user", "-created_at"], name="auth_session_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(fields=["user", "-created_at"], name="auth_password_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["user", "-created_at"], name="auth_event_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type", "-created_at"], name="auth_event_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationtoken",
            index=models.Index(fields=["user", "kind"], name="auth_token_user_kind_idx"),
        ),
    ]
