# Generated by Django 5.2.17 on 2026-08-05 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_remove_user_full_name_user_avatar_user_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(db_index=True, max_length=150, unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("module", models.CharField(db_index=True, max_length=100, verbose_name="Module")),
                ("category", models.CharField(default="general", max_length=100, verbose_name="Category")),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "scope",
                    models.CharField(
                        choices=[("platform", "Platform"), ("tenant", "Tenant")],
                        db_index=True,
                        default="tenant",
                        max_length=20,
                        verbose_name="Scope",
                    ),
                ),
                ("is_system", models.BooleanField(default=False, verbose_name="System")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["module", "category", "code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("is_protected", models.BooleanField(db_index=True, default=False, verbose_name="Protected")),
                ("is_default", models.BooleanField(db_index=True, default=False, verbose_name="Default")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoleAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("action", models.CharField(db_index=True, max_length=64, verbose_name="Action")),
                ("details", models.JSONField(default=dict, verbose_name="Details")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role audit log",
                "verbose_name_plural": "Role audit logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("code", models.CharField(max_length=100, verbose_name="Code")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role group",
                "verbose_name_plural": "Role groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoleGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="rbac.rolegroup",
                        verbose_name="Group",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role group membership",
                "verbose_name_plural": "Role group memberships",
                "ordering": ["group", "role"],
            },
        ),
        migrations.AddField(
            model_name="rolegroup",
            name="roles",
            field=models.ManyToManyField(
                related_name="groups",
                through="rbac.RoleGroupMembership",
                through_fields=("group", "role"),
                to="rbac.role",
                verbose_name="Roles",
            ),
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "child_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="rbac.role",
                        verbose_name="Child role",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_links",
                        to="rbac.role",
                        verbose_name="Parent role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role hierarchy",
                "verbose_name_plural": "Role hierarchy",
                "ordering": ["child_role", "parent_role"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="parents",
            field=models.ManyToManyField(
                related_name="children",
                through="rbac.RoleHierarchy",
                through_fields=("child_role", "parent_role"),
                to="rbac.role",
                verbose_name="Parent roles",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("allow", models.BooleanField(default=True, verbose_name="Allow")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_links",
                        to="rbac.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_links",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role permission",
                "verbose_name_plural": "Role permissions",
                "ordering": ["role", "permission"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                related_name="roles",
                through="rbac.RolePermission",
                through_fields=("role", "permission"),
                to="rbac.permission",
                verbose_name="Permissions",
            ),
        ),
        migrations.CreateModel(
            name="RoleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("version", models.PositiveIntegerField(default=1, verbose_name="Version")),
                ("snapshot", models.JSONField(default=dict, verbose_name="Snapshot")),
                ("reason", models.CharField(blank=True, default="", max_length=255, verbose_name="Reason")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role version",
                "verbose_name_plural": "Role versions",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("allow", models.BooleanField(default=True, verbose_name="Allow")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_overrides",
                        to="rbac.permission",
                        verbose_name="Permission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User permission override",
                "verbose_name_plural": "User permission overrides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Primary role")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Active")),
                ("reason", models.CharField(blank=True, default="", max_length=255, verbose_name="Reason")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="rbac.role",
                        verbose_name="Role",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User role assignment",
                "verbose_name_plural": "User role assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module", "category"], name="rbac_perm_module_cat_idx"),
        ),
        migrations.AddConstraint(
            model_name="rolegroupmembership",
            constraint=models.UniqueConstraint(fields=("group", "role"), name="rbac_groupmem_group_role_uniq"),
        ),
        migrations.AddConstraint(
            model_name="rolegroup",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="rbac_group_tenant_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="rolehierarchy",
            constraint=models.UniqueConstraint(
                fields=("child_role", "parent_role"), name="rbac_hierarchy_child_parent_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(fields=("role", "permission"), name="rbac_roleperm_role_perm_uniq"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="rbac_role_tenant_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="roleversion",
            constraint=models.UniqueConstraint(fields=("role", "version"), name="rbac_roleversion_role_version_uniq"),
        ),
        migrations.AddConstraint(
            model_name="userpermissionoverride",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "permission"), name="rbac_override_tenant_user_perm_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="userroleassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user", "role"), name="rbac_assignment_tenant_user_role_uniq"
            ),
        ),
    ]
