# Generated by Django 5.2.17 on 2026-08-07 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Supplier code")),
                ("legal_name", models.CharField(max_length=255, verbose_name="Legal name")),
                ("display_name", models.CharField(max_length=255, verbose_name="Display name")),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("distributor", "Distributor"),
                            ("wholesaler", "Wholesaler"),
                            ("importer", "Importer"),
                            ("agent", "Agent"),
                            ("service_provider", "Service Provider"),
                        ],
                        default="distributor",
                        max_length=40,
                        verbose_name="Supplier type",
                    ),
                ),
                (
                    "supplier_category",
                    models.CharField(default="Pharmaceuticals", max_length=100, verbose_name="Supplier category"),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Registration number"),
                ),
                ("tax_number", models.CharField(blank=True, default="", max_length=100, verbose_name="Tax number")),
                ("vat_number", models.CharField(blank=True, default="", max_length=100, verbose_name="VAT number")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("blacklisted", "Blacklisted"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="supplier_logos/", verbose_name="Logo")),
                ("website", models.URLField(blank=True, default="", verbose_name="Website")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "primary_contact_name",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Primary contact name"),
                ),
                (
                    "secondary_contact_name",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Secondary contact name"),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Phone")),
                ("mobile", models.CharField(blank=True, default="", max_length=32, verbose_name="Mobile")),
                ("whatsapp", models.CharField(blank=True, default="", max_length=32, verbose_name="WhatsApp")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Support email"),
                ),
                ("fax", models.CharField(blank=True, default="", max_length=32, verbose_name="Fax")),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="State")),
                ("city", models.CharField(default="Sanaa", max_length=100, verbose_name="City")),
                ("district", models.CharField(blank=True, default="", max_length=100, verbose_name="District")),
                ("postal_code", models.CharField(blank=True, default="", max_length=20, verbose_name="Postal code")),
                ("street", models.CharField(blank=True, default="", max_length=255, verbose_name="Street")),
                ("building", models.CharField(blank=True, default="", max_length=100, verbose_name="Building")),
                ("google_maps_url", models.URLField(blank=True, default="", verbose_name="Google Maps URL")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True, verbose_name="Longitude"
                    ),
                ),
                ("default_currency", models.CharField(default="YER", max_length=10, verbose_name="Default currency")),
                ("payment_terms", models.CharField(default="Net 30", max_length=100, verbose_name="Payment terms")),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Credit limit"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Opening balance"),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Current balance"),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(default="bank_transfer", max_length=50, verbose_name="Preferred payment method"),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=150, verbose_name="Bank name")),
                (
                    "bank_account",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Bank account"),
                ),
                ("iban", models.CharField(blank=True, default="", max_length=50, verbose_name="IBAN")),
                ("swift", models.CharField(blank=True, default="", max_length=30, verbose_name="SWIFT code")),
                ("tax_category", models.CharField(default="standard", max_length=50, verbose_name="Tax category")),
                (
                    "business_license",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Business license"),
                ),
                (
                    "commercial_registration",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Commercial registration"),
                ),
                (
                    "drug_license",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Drug license"),
                ),
                ("license_expiry_date", models.DateField(blank=True, null=True, verbose_name="License expiry date")),
                ("insurance_info", models.TextField(blank=True, default="", verbose_name="Insurance information")),
                ("is_preferred", models.BooleanField(default=False, verbose_name="Is preferred supplier")),
                ("is_blacklisted", models.BooleanField(default=False, verbose_name="Is blacklisted")),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name="Rating (1-5)"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=20,
                        verbose_name="Risk level",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["display_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="suppliers_supplier_tenant_code_uniq"),
                    models.UniqueConstraint(
                        fields=("tenant", "legal_name"), name="suppliers_supplier_tenant_legal_name_uniq"
                    ),
                ],
            },
        ),
    ]
