# Generated by Django 5.2.17 on 2026-08-14 21:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, unique=True, verbose_name="Add-On Code")),
                ("name", models.CharField(max_length=150, verbose_name="Add-On Name")),
                ("feature_key", models.CharField(max_length=100, verbose_name="Granted Feature Key")),
                ("grant_amount", models.IntegerField(default=1, verbose_name="Granted Limit Quantity")),
                ("price_amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Price Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing Cycle",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Add-On",
                "verbose_name_plural": "Add-Ons",
                "db_table": "saas_add_ons",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, unique=True, verbose_name="Coupon Code")),
                ("name", models.CharField(max_length=150, verbose_name="Coupon Name")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage Discount"), ("fixed_amount", "Fixed Amount Discount")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Discount Value"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "max_redemptions",
                    models.IntegerField(default=-1, verbose_name="Max Redemptions (-1 for Unlimited)"),
                ),
                ("times_redeemed", models.IntegerField(default=0, verbose_name="Times Redeemed")),
                ("expiry_date", models.DateTimeField(blank=True, null=True, verbose_name="Expiry Date")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "db_table": "saas_coupons",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("provider_name", models.CharField(default="mock", max_length=60, verbose_name="Provider Name")),
                (
                    "external_token_id",
                    models.CharField(db_index=True, max_length=150, verbose_name="External Provider Token ID"),
                ),
                ("brand", models.CharField(blank=True, default="Visa", max_length=50, verbose_name="Card Brand")),
                ("last4", models.CharField(blank=True, default="4242", max_length=4, verbose_name="Last 4 Digits")),
                ("exp_month", models.IntegerField(default=12, verbose_name="Expiry Month")),
                ("exp_year", models.IntegerField(default=2030, verbose_name="Expiry Year")),
                ("is_default", models.BooleanField(default=True, verbose_name="Is Default Payment Method")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "saas_payment_methods",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, unique=True, verbose_name="Plan Code")),
                ("name", models.CharField(max_length=150, verbose_name="Plan Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Plan Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_public", models.BooleanField(default=True, verbose_name="Is Publicly Available")),
                ("sort_order", models.IntegerField(default=0, verbose_name="Display Sort Order")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Plan",
                "verbose_name_plural": "SaaS Plans",
                "db_table": "saas_plans",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("version_number", models.IntegerField(default=1, verbose_name="Version Number")),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Effective Date"),
                ),
                ("is_current", models.BooleanField(default=True, verbose_name="Is Current Active Version")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="saas.plan",
                        verbose_name="SaaS Plan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Version",
                "verbose_name_plural": "Plan Versions",
                "db_table": "saas_plan_versions",
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing Cycle",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "price_amount",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Recurring Price Amount"),
                ),
                (
                    "setup_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="One-Time Setup Fee"),
                ),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Effective From"),
                ),
                ("effective_until", models.DateTimeField(blank=True, null=True, verbose_name="Effective Until")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="saas.planversion",
                        verbose_name="Plan Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Price",
                "verbose_name_plural": "Plan Prices",
                "db_table": "saas_plan_prices",
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "feature_key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Feature Key (e.g. max_users, max_branches, advanced_reports)",
                    ),
                ),
                ("feature_name", models.CharField(max_length=150, verbose_name="Feature Name")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Is Feature Enabled")),
                ("limit_value", models.IntegerField(default=-1, verbose_name="Limit Value (-1 for Unlimited)")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Feature Metadata")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="saas.planversion",
                        verbose_name="Plan Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
                "db_table": "saas_plan_features",
            },
        ),
        migrations.CreateModel(
            name="SaaSInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Invoice Number (SINV)"),
                ),
                ("billing_period_start", models.DateTimeField(verbose_name="Billing Period Start")),
                ("billing_period_end", models.DateTimeField(verbose_name="Billing Period End")),
                ("issue_date", models.DateField(default=django.utils.timezone.now, verbose_name="Issue Date")),
                ("due_date", models.DateField(verbose_name="Due Date")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Subtotal Amount"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Discount Amount"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Tax Amount"),
                ),
                (
                    "credits_applied",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Credits Applied"),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Total Amount"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open / Issued"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("past_due", "Past Due"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                        verbose_name="Invoice Status",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="Paid Timestamp")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Invoice",
                "verbose_name_plural": "SaaS Invoices",
                "db_table": "saas_invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "discount_applied",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Discount Amount Applied"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="saas.coupon",
                        verbose_name="Coupon",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_redemptions",
                        to="saas.saasinvoice",
                        verbose_name="SaaS Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Redemption",
                "verbose_name_plural": "Coupon Redemptions",
                "db_table": "saas_coupon_redemptions",
            },
        ),
        migrations.CreateModel(
            name="SaaSInvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("plan_fee", "Subscription Plan Fee"),
                            ("add_on", "Add-On Fee"),
                            ("overage", "Usage Overage Charge"),
                            ("proration_credit", "Proration Credit Adjustment"),
                            ("discount", "Discount"),
                            ("tax", "Tax Charge"),
                            ("one_time", "One-Time Charge"),
                        ],
                        default="plan_fee",
                        max_length=30,
                        verbose_name="Line Item Type",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Line Description")),
                ("quantity", models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name="Quantity")),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Unit Price")),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Line Total Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="saas.saasinvoice",
                        verbose_name="SaaS Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Invoice Line",
                "verbose_name_plural": "SaaS Invoice Lines",
                "db_table": "saas_invoice_lines",
            },
        ),
        migrations.CreateModel(
            name="SaaSPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Payment Number (SPAY)"),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Payment Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Payment Status",
                    ),
                ),
                ("provider_name", models.CharField(default="mock", max_length=60, verbose_name="Provider Name")),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="External Transaction ID"),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=100, verbose_name="Error Code")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Error Message")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="saas.saasinvoice",
                        verbose_name="SaaS Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Payment",
                "verbose_name_plural": "SaaS Payments",
                "db_table": "saas_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaaSPaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("refund_number", models.CharField(db_index=True, max_length=60, verbose_name="Refund Number (SRFD)")),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Refund Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                ("reason", models.TextField(blank=True, default="", verbose_name="Refund Reason")),
                (
                    "external_refund_id",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="External Provider Refund ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="saas.saaspayment",
                        verbose_name="SaaS Payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Payment Refund",
                "verbose_name_plural": "SaaS Payment Refunds",
                "db_table": "saas_payment_refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaaSSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "subscription_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Subscription Number (SUB)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("grace_period", "Grace Period"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("incomplete", "Incomplete"),
                            ("pending", "Pending Activation"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=30,
                        verbose_name="Subscription Status",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing Cycle",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Start Date")),
                ("trial_start", models.DateTimeField(blank=True, null=True, verbose_name="Trial Start Date")),
                ("trial_end", models.DateTimeField(blank=True, null=True, verbose_name="Trial End Date")),
                (
                    "current_period_start",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Current Period Start"),
                ),
                ("current_period_end", models.DateTimeField(verbose_name="Current Period End")),
                ("next_billing_date", models.DateTimeField(blank=True, null=True, verbose_name="Next Billing Date")),
                ("cancel_at_period_end", models.BooleanField(default=False, verbose_name="Cancel At Period End")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At")),
                ("cancellation_reason", models.TextField(blank=True, default="", verbose_name="Cancellation Reason")),
                ("grace_period_end", models.DateTimeField(blank=True, null=True, verbose_name="Grace Period End")),
                (
                    "external_provider_id",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="External Provider Sub ID"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Subscription Metadata")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="saas.plan",
                        verbose_name="Subscribed Plan",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="saas.planversion",
                        verbose_name="Subscribed Plan Version",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS Subscription",
                "verbose_name_plural": "SaaS Subscriptions",
                "db_table": "saas_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaaSLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "license_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="License Number (LIC)"),
                ),
                (
                    "license_key",
                    models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Secure License Key"),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription License"),
                            ("trial", "Trial License"),
                            ("enterprise", "Enterprise On-Prem/Hybrid License"),
                            ("evaluation", "Evaluation License"),
                        ],
                        default="subscription",
                        max_length=30,
                        verbose_name="License Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active License"),
                            ("trial", "Trial License"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="License Status",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Issued Timestamp"),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Expiry Timestamp")),
                (
                    "entitlements_snapshot",
                    models.JSONField(blank=True, default=dict, verbose_name="Entitlements Snapshot JSON"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="saas.saassubscription",
                        verbose_name="Associated SaaS Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS License",
                "verbose_name_plural": "SaaS Licenses",
                "db_table": "saas_licenses",
            },
        ),
        migrations.AddField(
            model_name="saasinvoice",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="saas.saassubscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.CreateModel(
            name="PaymentFailureLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("attempt_number", models.IntegerField(default=1, verbose_name="Attempt Number")),
                ("error_code", models.CharField(max_length=100, verbose_name="Error Code")),
                ("error_message", models.TextField(verbose_name="Error Message")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Next Scheduled Retry")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_logs",
                        to="saas.saassubscription",
                        verbose_name="SaaS Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Failure Log",
                "verbose_name_plural": "Payment Failure Logs",
                "db_table": "saas_payment_failure_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "balance_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Balance Amount"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Credit Balance",
                "verbose_name_plural": "Tenant Credit Balances",
                "db_table": "saas_tenant_credits",
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Transaction Amount")),
                (
                    "transaction_type",
                    models.CharField(max_length=30, verbose_name="Transaction Type (grant, usage, refund)"),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Transaction Description")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_transactions",
                        to="saas.saasinvoice",
                        verbose_name="SaaS Invoice",
                    ),
                ),
                (
                    "tenant_credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="saas.tenantcredit",
                        verbose_name="Tenant Credit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Transaction",
                "verbose_name_plural": "Credit Transactions",
                "db_table": "saas_credit_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(fields=("plan", "version_number"), name="saas_plan_version_uniq"),
        ),
        migrations.AddConstraint(
            model_name="planfeature",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "feature_key"), name="saas_plan_ver_feature_uniq"
            ),
        ),
    ]
