# Generated by Django 5.2.17 on 2026-08-14 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("customers", "0001_initial"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommerceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("order_number", models.CharField(db_index=True, max_length=60, verbose_name="Order Number (ORD)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Order"),
                            ("pending", "Pending Order"),
                            ("confirmed", "Confirmed"),
                            ("payment_pending", "Payment Pending"),
                            ("paid", "Paid"),
                            ("processing", "Processing / Picking"),
                            ("ready_for_pickup", "Ready For Pickup"),
                            ("out_for_delivery", "Out For Delivery"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid Successfully"),
                            ("failed", "Payment Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("pickup", "Branch / Store Pickup"),
                            ("standard", "Standard Delivery"),
                            ("express", "Express Courier Delivery"),
                        ],
                        default="standard",
                        max_length=30,
                        verbose_name="Delivery Method",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Subtotal Amount"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Discount Amount"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Tax Amount"),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Shipping Fee"),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Grand Total Amount"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                ("shipping_address", models.TextField(blank=True, default="", verbose_name="Shipping Address")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120, verbose_name="Idempotency Key"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Customer Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_orders",
                        to="branches.branch",
                        verbose_name="Fulfillment Branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commerce_orders",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commerce_orders",
                        to="warehouses.warehouse",
                        verbose_name="Fulfillment Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commerce Order",
                "verbose_name_plural": "Commerce Orders",
                "db_table": "commerce_orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommercePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Payment Number (CPAY)"),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Payment Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "payment_method",
                    models.CharField(
                        default="card", max_length=50, verbose_name="Payment Method (card, cod, wallet, b2b_credit)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid Successfully"),
                            ("failed", "Payment Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "external_tx_id",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="External Gateway Transaction ID"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="commerce.commerceorder",
                        verbose_name="Commerce Order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commerce Payment",
                "verbose_name_plural": "Commerce Payments",
                "db_table": "commerce_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommerceRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("refund_number", models.CharField(db_index=True, max_length=60, verbose_name="Refund Number (CRFD)")),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Refund Amount")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                ("reason", models.TextField(blank=True, default="", verbose_name="Refund Reason")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="commerce.commercepayment",
                        verbose_name="Commerce Payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commerce Refund",
                "verbose_name_plural": "Commerce Refunds",
                "db_table": "commerce_refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=100, verbose_name="Courier Tracking Number"),
                ),
                ("courier_name", models.CharField(max_length=100, verbose_name="Courier Provider Name")),
                (
                    "estimated_delivery",
                    models.DateTimeField(blank=True, null=True, verbose_name="Estimated Delivery Timestamp"),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="Delivered Timestamp")),
                (
                    "delivery_notes",
                    models.TextField(blank=True, default="", verbose_name="Delivery Instructions / Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_record",
                        to="commerce.commerceorder",
                        verbose_name="Commerce Order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Delivery",
                "verbose_name_plural": "Order Deliveries",
                "db_table": "commerce_order_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("file_url", models.URLField(max_length=500, verbose_name="Secure Storage File URL")),
                ("file_type", models.CharField(default="image/jpeg", max_length=20, verbose_name="MIME Content Type")),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded - Awaiting Review"),
                            ("under_review", "Under Pharmacist Review"),
                            ("approved", "Approved by Pharmacist"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=30,
                        verbose_name="Pharmacist Review Status",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Reviewed Timestamp")),
                (
                    "pharmacist_notes",
                    models.TextField(blank=True, default="", verbose_name="Pharmacist Clinical Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_prescriptions",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="commerce.commerceorder",
                        verbose_name="Commerce Order",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_order_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewing Pharmacist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Prescription",
                "verbose_name_plural": "Order Prescriptions",
                "db_table": "commerce_order_prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("display_name", models.CharField(max_length=200, verbose_name="Digital Display Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Product Description & Usage")),
                (
                    "retail_price",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Online B2C Retail Price"),
                ),
                (
                    "b2b_price",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Online B2B Wholesale Price"),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="Is Published Online")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Is Featured Product")),
                (
                    "is_prescription_required",
                    models.BooleanField(default=False, verbose_name="Prescription Required for Purchase"),
                ),
                ("min_order_qty", models.IntegerField(default=1, verbose_name="Minimum Order Quantity")),
                ("max_order_qty", models.IntegerField(default=100, verbose_name="Maximum Order Quantity")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_products",
                        to="medicines.medicine",
                        verbose_name="Medicine Master Item",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Product",
                "verbose_name_plural": "Store Products",
                "db_table": "commerce_store_products",
            },
        ),
        migrations.CreateModel(
            name="CommerceOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name="Order Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Unit Price Snapshot"),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Discount Amount"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Tax Amount"),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Total Line Amount"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commerce_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine Master Item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="commerce.commerceorder",
                        verbose_name="Commerce Order",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="commerce.storeproduct",
                        verbose_name="Store Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commerce Order Line",
                "verbose_name_plural": "Commerce Order Lines",
                "db_table": "commerce_order_lines",
            },
        ),
        migrations.CreateModel(
            name="TenantStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, verbose_name="Store Code")),
                ("name", models.CharField(max_length=150, verbose_name="Storefront Display Name")),
                (
                    "domain",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Custom Domain or Subdomain"
                    ),
                ),
                ("logo_url", models.URLField(blank=True, default="", max_length=500, verbose_name="Brand Logo URL")),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Store Currency Code")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Storefront"),
                            ("maintenance", "Storefront Under Maintenance"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Storefront Status",
                    ),
                ),
                ("is_b2b_enabled", models.BooleanField(default=True, verbose_name="Enable B2B Wholesale Commerce")),
                ("is_b2c_enabled", models.BooleanField(default=True, verbose_name="Enable B2C Retail Commerce")),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="Standard Delivery Fee"
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="Free Delivery Threshold"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Store",
                "verbose_name_plural": "Tenant Stores",
                "db_table": "commerce_tenant_stores",
            },
        ),
        migrations.AddField(
            model_name="storeproduct",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="commerce.tenantstore",
                verbose_name="Tenant Store",
            ),
        ),
        migrations.CreateModel(
            name="StoreCoupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(db_index=True, max_length=60, verbose_name="Coupon Code")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage Discount"), ("fixed_amount", "Fixed Amount Discount")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Discount Value"),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="Minimum Order Subtotal"
                    ),
                ),
                ("usage_limit", models.IntegerField(default=-1, verbose_name="Total Usage Limit (-1 for Unlimited)")),
                ("times_used", models.IntegerField(default=0, verbose_name="Times Used")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Expiry Timestamp")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="commerce.tenantstore",
                        verbose_name="Tenant Store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Coupon",
                "verbose_name_plural": "Store Coupons",
                "db_table": "commerce_store_coupons",
            },
        ),
        migrations.AddField(
            model_name="commerceorder",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="commerce.tenantstore",
                verbose_name="Tenant Store",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Guest Session Key"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="Currency Code")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="customers.customer",
                        verbose_name="Customer Profile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="commerce.tenantstore",
                        verbose_name="Tenant Store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
                "db_table": "commerce_carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name="Item Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Unit Price Snapshot"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commerce.cart",
                        verbose_name="Shopping Cart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="commerce.storeproduct",
                        verbose_name="Store Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "commerce_cart_items",
                "constraints": [
                    models.UniqueConstraint(fields=("cart", "product"), name="commerce_cart_product_uniq")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tenantstore",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="commerce_store_tenant_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="storeproduct",
            constraint=models.UniqueConstraint(fields=("store", "medicine"), name="commerce_store_medicine_uniq"),
        ),
        migrations.AddConstraint(
            model_name="storecoupon",
            constraint=models.UniqueConstraint(fields=("store", "code"), name="commerce_store_coupon_uniq"),
        ),
    ]
