# Generated by Django 5.2.17 on 2026-08-07 04:53

import apps.companies.models.settings
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("legal_name", models.CharField(max_length=200, verbose_name="Legal name")),
                (
                    "commercial_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Commercial name"),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Code")),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("pharmacy_group", "Pharmacy Group / Chain"),
                            ("retail_pharmacy", "Retail Pharmacy"),
                            ("wholesale_distributor", "Wholesale Distributor"),
                            ("clinic_network", "Clinic / Hospital Network"),
                            ("single_store", "Single Store"),
                        ],
                        default="retail_pharmacy",
                        max_length=50,
                        verbose_name="Business type",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="License number"),
                ),
                ("tax_number", models.CharField(blank=True, default="", max_length=100, verbose_name="Tax number")),
                (
                    "commercial_registration",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Commercial registration"),
                ),
                (
                    "vat_registration",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="VAT registration"),
                ),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="City")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="State")),
                ("postal_code", models.CharField(blank=True, default="", max_length=20, verbose_name="Postal code")),
                ("address", models.TextField(blank=True, default="", verbose_name="Address")),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Phone")),
                ("mobile", models.CharField(blank=True, default="", max_length=32, verbose_name="Mobile")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, default="", verbose_name="Website")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="company_logos/", verbose_name="Logo")),
                ("primary_color", models.CharField(default="#007bff", max_length=20, verbose_name="Primary color")),
                (
                    "secondary_color",
                    models.CharField(default="#6c757d", max_length=20, verbose_name="Secondary color"),
                ),
                ("currency", models.CharField(default="YER", max_length=10, verbose_name="Currency")),
                ("timezone", models.CharField(default="UTC", max_length=64, verbose_name="Timezone")),
                ("language", models.CharField(default="en", max_length=10, verbose_name="Language")),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Fiscal year start month"),
                ),
                ("business_hours", models.JSONField(blank=True, default=dict, verbose_name="Business hours")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("general_settings", models.JSONField(blank=True, default=dict, verbose_name="General settings")),
                ("financial_settings", models.JSONField(blank=True, default=dict, verbose_name="Financial settings")),
                ("inventory_settings", models.JSONField(blank=True, default=dict, verbose_name="Inventory settings")),
                ("sales_settings", models.JSONField(blank=True, default=dict, verbose_name="Sales settings")),
                ("purchase_settings", models.JSONField(blank=True, default=dict, verbose_name="Purchase settings")),
                ("pos_settings", models.JSONField(blank=True, default=dict, verbose_name="POS settings")),
                ("barcode_settings", models.JSONField(blank=True, default=dict, verbose_name="Barcode settings")),
                ("receipt_settings", models.JSONField(blank=True, default=dict, verbose_name="Receipt settings")),
                (
                    "tax_configuration",
                    models.JSONField(
                        blank=True,
                        default=apps.companies.models.settings.default_company_tax_config,
                        verbose_name="Tax configuration",
                    ),
                ),
                ("invoice_numbering", models.JSONField(blank=True, default=dict, verbose_name="Invoice numbering")),
                (
                    "document_prefixes",
                    models.JSONField(
                        blank=True,
                        default=apps.companies.models.settings.default_document_prefixes,
                        verbose_name="Document prefixes",
                    ),
                ),
                ("default_currency", models.CharField(default="YER", max_length=10, verbose_name="Default currency")),
                ("default_language", models.CharField(default="en", max_length=10, verbose_name="Default language")),
                (
                    "theme_configuration",
                    models.JSONField(blank=True, default=dict, verbose_name="Theme configuration"),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("tenant", "legal_name"), name="companies_company_tenant_legal_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="companies_company_tenant_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(fields=("tenant", "slug"), name="companies_company_tenant_slug_uniq"),
        ),
    ]
