# Generated by Django 5.2.17 on 2026-08-07 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtcClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=20, verbose_name="ATC Code")),
                ("level", models.PositiveSmallIntegerField(verbose_name="ATC Level (1-5)")),
                ("name_en", models.CharField(max_length=200, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=200, verbose_name="Arabic Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="references.atcclassification",
                        verbose_name="Parent ATC Code",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "ATC Classification",
                "verbose_name_plural": "ATC Classifications",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_atc_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="DosageForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Form Code")),
                ("name_en", models.CharField(max_length=100, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=100, verbose_name="Arabic Name")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dosage Form",
                "verbose_name_plural": "Dosage Forms",
                "ordering": ["display_order", "name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_dosageform_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Manufacturer Code")),
                ("legal_name", models.CharField(max_length=200, verbose_name="Legal Name")),
                ("display_name", models.CharField(max_length=200, verbose_name="Display Name")),
                (
                    "country_of_origin",
                    models.CharField(default="Yemen", max_length=100, verbose_name="Country of Origin"),
                ),
                ("address", models.TextField(blank=True, default="", verbose_name="Address")),
                ("website", models.URLField(blank=True, default="", verbose_name="Website")),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Contact Phone"),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Registration Number"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": ["display_name"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_manufacturer_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicineCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Category Code")),
                ("name_en", models.CharField(max_length=150, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=150, verbose_name="Arabic Name")),
                ("slug", models.SlugField(max_length=150, verbose_name="Slug")),
                ("icon", models.CharField(blank=True, default="", max_length=100, verbose_name="Icon")),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="references.medicinecategory",
                        verbose_name="Parent Category",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Category",
                "verbose_name_plural": "Medicine Categories",
                "ordering": ["display_order", "name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_category_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="PackageType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=30, verbose_name="Package Code")),
                ("name_en", models.CharField(max_length=50, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=50, verbose_name="Arabic Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Type",
                "verbose_name_plural": "Package Types",
                "ordering": ["name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_packagetype_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteOfAdministration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=30, verbose_name="Route Code")),
                ("name_en", models.CharField(max_length=100, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=100, verbose_name="Arabic Name")),
                ("abbreviation", models.CharField(blank=True, default="", max_length=20, verbose_name="Abbreviation")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route of Administration",
                "verbose_name_plural": "Routes of Administration",
                "ordering": ["name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_route_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Condition Code")),
                ("name_en", models.CharField(max_length=150, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=150, verbose_name="Arabic Name")),
                (
                    "min_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Min Temp (°C)"
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Max Temp (°C)"
                    ),
                ),
                ("requires_refrigeration", models.BooleanField(default=False, verbose_name="Requires Refrigeration")),
                ("protect_from_light", models.BooleanField(default=False, verbose_name="Protect From Light")),
                ("humidity_controlled", models.BooleanField(default=False, verbose_name="Humidity Controlled")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Condition",
                "verbose_name_plural": "Storage Conditions",
                "ordering": ["name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_storage_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="StrengthUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=30, verbose_name="Unit Code")),
                ("name_en", models.CharField(max_length=50, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=50, verbose_name="Arabic Name")),
                ("symbol", models.CharField(max_length=20, verbose_name="Symbol")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strength Unit",
                "verbose_name_plural": "Strength Units",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_strengthunit_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=30, verbose_name="Tax Code")),
                ("name_en", models.CharField(max_length=100, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=100, verbose_name="Arabic Name")),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Tax Rate %"),
                ),
                ("is_exempt", models.BooleanField(default=False, verbose_name="Is Exempt")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Category",
                "verbose_name_plural": "Tax Categories",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_taxcategory_tenant_code_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=30, verbose_name="UOM Code")),
                ("name_en", models.CharField(max_length=50, verbose_name="English Name")),
                ("name_ar", models.CharField(max_length=50, verbose_name="Arabic Name")),
                ("symbol", models.CharField(blank=True, default="", max_length=20, verbose_name="Symbol")),
                ("unit_type", models.CharField(default="both", max_length=30, verbose_name="Unit Type")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_system", models.BooleanField(default=False, verbose_name="Is System Standard")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["name_en"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenant", "code"), name="references_uom_tenant_code_uniq")
                ],
            },
        ),
    ]
