# Generated by Django 5.2.17 on 2026-08-07 05:12

import apps.branches.models.settings
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Branch code")),
                ("name", models.CharField(max_length=200, verbose_name="Branch name")),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Display name"),
                ),
                ("slug", models.SlugField(max_length=100, verbose_name="Slug")),
                (
                    "branch_type",
                    models.CharField(
                        choices=[
                            ("retail_pharmacy", "Retail Pharmacy"),
                            ("warehouse", "Warehouse"),
                            ("distribution_center", "Distribution Center"),
                            ("head_office", "Head Office"),
                            ("clinic_pharmacy", "Clinic Pharmacy"),
                            ("hospital_pharmacy", "Hospital Pharmacy"),
                            ("virtual_branch", "Virtual Branch"),
                        ],
                        default="retail_pharmacy",
                        max_length=50,
                        verbose_name="Branch type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("temporarily_closed", "Temporarily Closed"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Phone")),
                ("mobile", models.CharField(blank=True, default="", max_length=32, verbose_name="Mobile")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, default="", verbose_name="Website")),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="City")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="State")),
                ("district", models.CharField(blank=True, default="", max_length=100, verbose_name="District")),
                ("postal_code", models.CharField(blank=True, default="", max_length=20, verbose_name="Postal code")),
                ("full_address", models.TextField(blank=True, default="", verbose_name="Full address")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Longitude"
                    ),
                ),
                ("google_maps_link", models.URLField(blank=True, default="", verbose_name="Google Maps link")),
                ("timezone", models.CharField(default="UTC", max_length=64, verbose_name="Timezone")),
                ("working_days", models.JSONField(blank=True, default=list, verbose_name="Working days")),
                ("working_hours", models.JSONField(blank=True, default=dict, verbose_name="Working hours")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="branch_logos/", verbose_name="Logo")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_branches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Branch manager",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BranchSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("working_hours", models.JSONField(blank=True, default=dict, verbose_name="Working hours")),
                ("business_days", models.JSONField(blank=True, default=list, verbose_name="Business days")),
                (
                    "currency_override",
                    models.CharField(blank=True, default="", max_length=10, verbose_name="Currency override"),
                ),
                ("receipt_template", models.JSONField(blank=True, default=dict, verbose_name="Receipt template")),
                (
                    "invoice_prefix",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Invoice prefix"),
                ),
                (
                    "tax_settings",
                    models.JSONField(
                        blank=True,
                        default=apps.branches.models.settings.default_branch_tax_config,
                        verbose_name="Tax settings",
                    ),
                ),
                ("pos_settings", models.JSONField(blank=True, default=dict, verbose_name="POS settings")),
                ("barcode_settings", models.JSONField(blank=True, default=dict, verbose_name="Barcode settings")),
                ("inventory_settings", models.JSONField(blank=True, default=dict, verbose_name="Inventory settings")),
                (
                    "notification_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Notification settings"),
                ),
                ("printer_settings", models.JSONField(blank=True, default=dict, verbose_name="Printer settings")),
                ("theme_settings", models.JSONField(blank=True, default=dict, verbose_name="Theme settings")),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_settings",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Settings",
                "verbose_name_plural": "Branch Settings",
            },
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(fields=("company", "name"), name="branches_branch_company_name_uniq"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(fields=("company", "code"), name="branches_branch_company_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(fields=("company", "slug"), name="branches_branch_company_slug_uniq"),
        ),
    ]
