# Generated by Django 5.2.17 on 2026-08-09 01:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("inventory", "0001_initial"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "movement_number",
                    models.CharField(
                        db_index=True,
                        help_text="System generated movement code e.g. STK-2026-000001",
                        max_length=60,
                        verbose_name="Movement number",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening_balance", "Opening Balance"),
                            ("receipt", "Stock Receipt"),
                            ("issue", "Stock Issue"),
                            ("sale", "POS / Sales Issue"),
                            ("sale_return", "Sales Return"),
                            ("purchase_return", "Purchase Return"),
                            ("transfer_out", "Transfer Out"),
                            ("transfer_in", "Transfer In"),
                            ("adjustment_in", "Adjustment Increase (+)"),
                            ("adjustment_out", "Adjustment Decrease (-)"),
                            ("damage", "Damage Movement"),
                            ("expiry", "Expiry Movement"),
                            ("quarantine", "Move to Quarantine"),
                            ("quarantine_release", "Release from Quarantine"),
                            ("reservation", "Stock Reservation"),
                            ("reservation_release", "Reservation Release"),
                            ("correction", "Correction Movement"),
                            ("recall", "Batch Recall Movement"),
                            ("other", "Other Movement"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Movement type",
                    ),
                ),
                (
                    "movement_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Movement status",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Total movement quantity",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, default="Pcs", max_length=30, verbose_name="Unit of measure"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit cost"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total cost value"
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("goods_receipt", "Goods Receipt Note"),
                            ("sales_invoice", "Sales Invoice"),
                            ("sales_return", "Sales Return Document"),
                            ("transfer_request", "Stock Transfer Request"),
                            ("stock_count", "Physical Stock Count Sheet"),
                            ("adjustment", "Stock Adjustment Document"),
                            ("prescription", "Medical Prescription"),
                            ("manual", "Manual User Entry"),
                            ("other", "Other Reference Document"),
                        ],
                        default="",
                        max_length=50,
                        verbose_name="Reference document type",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="External reference ID"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="External reference code"
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=100, verbose_name="Movement reason")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("is_reversal", models.BooleanField(default=False, verbose_name="Is compensating reversal movement")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Unique key to prevent duplicate processing",
                        max_length=100,
                        verbose_name="Idempotency key",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed timestamp")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled timestamp")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who approved movement",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="inventory.batch",
                        verbose_name="Batch Header",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_stock_movements",
                        to="warehouses.storagelocation",
                        verbose_name="Destination Location",
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_stock_movements",
                        to="warehouses.warehouse",
                        verbose_name="Destination Warehouse",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="medicines.medicine",
                        verbose_name="Medicine Header",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User who performed movement",
                    ),
                ),
                (
                    "reversed_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="stock_movement.stockmovement",
                        verbose_name="Original movement reversed",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_stock_movements",
                        to="warehouses.storagelocation",
                        verbose_name="Source Location",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_stock_movements",
                        to="warehouses.warehouse",
                        verbose_name="Source Warehouse",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="warehouses.warehouse",
                        verbose_name="Primary Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Movement Line Quantity"),
                ),
                ("unit", models.CharField(blank=True, default="Pcs", max_length=30, verbose_name="Unit of Measure")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Cost"
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Line Cost"
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=100, verbose_name="Line Reason")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_lines",
                        to="inventory.batch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_movement_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Destination Location",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="stock_movement.stockmovement",
                        verbose_name="Stock Movement Document",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_movement_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Source Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement Line",
                "verbose_name_plural": "Stock Movement Lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "movement_type"], name="stock_movem_tenant__a01134_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "movement_status"], name="stock_movem_tenant__020953_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "created_at"], name="stock_movem_tenant__77aa67_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["tenant", "idempotency_key"], name="stock_movem_tenant__4e6952_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["reference_type", "reference_id"], name="stock_movem_referen_7268ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "movement_number"), name="stock_movement_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovementline",
            index=models.Index(fields=["movement", "medicine"], name="stock_movem_movemen_87e4d6_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovementline",
            index=models.Index(fields=["tenant", "batch"], name="stock_movem_tenant__8cd697_idx"),
        ),
    ]
