# Generated by Django 5.2.17 on 2026-08-11 21:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("customers", "0001_initial"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("sales", "0002_salesinvoiceline_returned_quantity"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("rx_number", models.CharField(db_index=True, max_length=60, verbose_name="Prescription Number (RX)")),
                ("rx_date", models.DateField(db_index=True, verbose_name="Prescription Date")),
                ("expiry_date", models.DateField(db_index=True, verbose_name="Prescription Expiry Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Prescription"),
                            ("pending_verification", "Pending Clinical Verification"),
                            ("verified", "Clinically Verified"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("fully_dispensed", "Fully Dispensed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Prescription Status",
                    ),
                ),
                (
                    "rx_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Prescription"),
                            ("controlled_class_a", "Controlled Substance Class A"),
                            ("controlled_class_b", "Controlled Substance Class B"),
                            ("narcotic", "Narcotic / Psychotropic Drug"),
                            ("chronic_refill", "Chronic Disease Refill"),
                            ("emergency", "Emergency Prescription"),
                        ],
                        db_index=True,
                        default="regular",
                        max_length=30,
                        verbose_name="Prescription Classification",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=200, verbose_name="Prescribing Doctor Name")),
                (
                    "doctor_license_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Doctor License / Registration Number"
                    ),
                ),
                (
                    "clinic_hospital_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Clinic / Hospital Name"),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Diagnosis Code (ICD-10 / Text)"
                    ),
                ),
                (
                    "diagnosis_description",
                    models.TextField(blank=True, default="", verbose_name="Diagnosis Description"),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="Is Clinically Verified")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="Verified At")),
                ("dispensed_at", models.DateTimeField(blank=True, null=True, verbose_name="Fully Dispensed At")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="customers.customer",
                        verbose_name="Patient / Customer",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dispensed By Pharmacist",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By Pharmacist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "prescriptions",
                "ordering": ["-rx_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDispense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "dispense_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Dispensation Number (DISP)"),
                ),
                ("dispensed_at", models.DateTimeField(db_index=True, verbose_name="Dispensed At")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed Dispensing"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="completed",
                        max_length=30,
                        verbose_name="Dispense Status",
                    ),
                ),
                (
                    "pharmacist_notes",
                    models.TextField(blank=True, default="", verbose_name="Pharmacist Dispensing Notes"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_dispensations",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_dispensations",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_prescription_dispensations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dispensed By Pharmacist",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensations",
                        to="prescriptions.prescription",
                        verbose_name="Prescription",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescription_dispensations",
                        to="sales.salesinvoice",
                        verbose_name="Linked POS Sales Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_dispensations",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Dispensation",
                "verbose_name_plural": "Prescription Dispensations",
                "db_table": "prescription_dispensations",
                "ordering": ["-dispensed_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "prescribed_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Prescribed Quantity"
                    ),
                ),
                (
                    "dispensed_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Dispensed Quantity"
                    ),
                ),
                (
                    "dosage",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Dosage (e.g. 500mg)"),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Frequency (e.g. 3 times daily)"
                    ),
                ),
                ("duration_days", models.PositiveIntegerField(default=1, verbose_name="Duration in Days")),
                (
                    "instructions",
                    models.TextField(blank=True, default="", verbose_name="Usage / Patient Instructions"),
                ),
                ("refills_allowed", models.PositiveIntegerField(default=0, verbose_name="Refills Allowed")),
                ("refills_remaining", models.PositiveIntegerField(default=0, verbose_name="Refills Remaining")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Dispensing"),
                            ("dispensed", "Fully Dispensed"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("cancelled", "Cancelled"),
                            ("substituted", "Substituted"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Line Dispensing Status",
                    ),
                ),
                ("is_substituted", models.BooleanField(default=False, verbose_name="Is Generic Substituted")),
                (
                    "substitution_reason",
                    models.CharField(blank=True, default="", max_length=250, verbose_name="Substitution Reason"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescription_lines",
                        to="medicines.medicine",
                        verbose_name="Prescribed Medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="prescriptions.prescription",
                        verbose_name="Prescription",
                    ),
                ),
                (
                    "substituted_medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituted_prescription_lines",
                        to="medicines.medicine",
                        verbose_name="Substituted Medicine",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Line",
                "verbose_name_plural": "Prescription Lines",
                "db_table": "prescription_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionDispenseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "dispensed_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Dispensed Quantity"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Selling Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Total Price"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="inventory.batch",
                        verbose_name="Dispensed Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "dispense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="prescriptions.prescriptiondispense",
                        verbose_name="Dispense Header",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="medicines.medicine",
                        verbose_name="Dispensed Medicine",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
                (
                    "prescription_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispense_lines",
                        to="prescriptions.prescriptionline",
                        verbose_name="Original Prescription Line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Dispense Line",
                "verbose_name_plural": "Prescription Dispense Lines",
                "db_table": "prescription_dispense_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["tenant", "status"], name="prescriptio_tenant__bb2f07_idx"),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["tenant", "customer"], name="prescriptio_tenant__76f73c_idx"),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(fields=["tenant", "rx_type"], name="prescriptio_tenant__0e2445_idx"),
        ),
        migrations.AddConstraint(
            model_name="prescription",
            constraint=models.UniqueConstraint(fields=("tenant", "rx_number"), name="prescription_tenant_number_uniq"),
        ),
        migrations.AddConstraint(
            model_name="prescriptiondispense",
            constraint=models.UniqueConstraint(
                fields=("tenant", "dispense_number"), name="prescription_dispense_tenant_number_uniq"
            ),
        ),
    ]
