# Generated by Django 5.2.17 on 2026-08-11 23:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("fiscal_year", models.PositiveIntegerField(db_index=True, verbose_name="Fiscal Year")),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(db_index=True, verbose_name="Period Number (1-12)"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Period Name (e.g. 2026-01)")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open Accounting Period"),
                            ("closed", "Closed Period"),
                            ("locked", "Locked Period (Audited)"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Period Status",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_periods",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Period",
                "verbose_name_plural": "Accounting Periods",
                "db_table": "gl_accounting_periods",
                "ordering": ["fiscal_year", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "account_code",
                    models.CharField(db_index=True, max_length=50, verbose_name="Account Code (e.g. 1100)"),
                ),
                ("account_name", models.CharField(max_length=200, verbose_name="Account Name")),
                (
                    "english_name",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="English Name"),
                ),
                ("arabic_name", models.CharField(blank=True, default="", max_length=200, verbose_name="Arabic Name")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue / Income"),
                            ("expense", "Expense"),
                            ("cost_of_goods_sold", "Cost of Goods Sold (COGS)"),
                            ("other_income", "Other Income"),
                            ("other_expense", "Other Expense"),
                        ],
                        db_index=True,
                        default="asset",
                        max_length=30,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "account_subtype",
                    models.CharField(
                        choices=[
                            ("cash", "Cash & Cash Equivalents"),
                            ("bank", "Bank Account"),
                            ("accounts_receivable", "Accounts Receivable (AR)"),
                            ("inventory", "Merchandise Inventory"),
                            ("fixed_asset", "Fixed Asset / Equipment"),
                            ("accounts_payable", "Accounts Payable (AP)"),
                            ("tax_payable", "Tax / VAT Payable"),
                            ("customer_credit", "Customer Credit Liability"),
                            ("supplier_credit", "Supplier Credit Asset"),
                            ("sales_revenue", "Sales Revenue"),
                            ("sales_returns", "Sales Returns & Allowances"),
                            ("purchase", "Purchases"),
                            ("cogs", "Cost of Goods Sold"),
                            ("operating_expense", "Operating Expense"),
                            ("other_income", "Other Income"),
                            ("other_expense", "Other Expense"),
                            ("capital", "Owner Capital"),
                            ("retained_earnings", "Retained Earnings"),
                        ],
                        default="cash",
                        max_length=40,
                        verbose_name="Account Subtype",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=20, verbose_name="Account Status"),
                ),
                ("is_system_account", models.BooleanField(default=False, verbose_name="Is System Account")),
                (
                    "is_control_account",
                    models.BooleanField(
                        default=False, verbose_name="Is Control Account (Non-postable summary parent)"
                    ),
                ),
                (
                    "allow_manual_posting",
                    models.BooleanField(default=True, verbose_name="Allow Manual Journal Posting"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chart_of_accounts",
                        to="branches.branch",
                        verbose_name="Branch Scope",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_accounts",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="general_ledger.chartofaccount",
                        verbose_name="Parent Account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart of Account",
                "verbose_name_plural": "Chart of Accounts",
                "db_table": "chart_of_accounts",
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="AccountMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("default_cash", "Default Cash Account"),
                            ("default_bank", "Default Bank Account"),
                            ("default_ar", "Default Accounts Receivable Account"),
                            ("default_ap", "Default Accounts Payable Account"),
                            ("default_sales_revenue", "Default Sales Revenue Account"),
                            ("default_sales_return", "Default Sales Returns Account"),
                            ("default_inventory", "Default Inventory Account"),
                            ("default_cogs", "Default COGS Account"),
                            ("default_output_tax", "Default Output Tax Account"),
                            ("default_input_tax", "Default Input Tax Account"),
                            ("default_customer_credit", "Default Customer Credit Account"),
                            ("default_supplier_credit", "Default Supplier Credit Account"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="Integration Mapping Purpose",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_mappings",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="general_ledger.chartofaccount",
                        verbose_name="Mapped Chart of Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Mapping",
                "verbose_name_plural": "Account Mappings",
                "db_table": "gl_account_mappings",
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "journal_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Journal Number (JRN)"),
                ),
                (
                    "journal_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name="Journal Date"),
                ),
                (
                    "posting_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name="Posting Date"),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50, verbose_name="Reference Type"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Reference ID"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Reference Number"
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50, verbose_name="Source Module"
                    ),
                ),
                ("description", models.TextField(verbose_name="Journal Transaction Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Journal"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("posted", "Posted Journal (Immutable)"),
                            ("reversed", "Reversed Journal"),
                            ("voided", "Voided"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Journal Status",
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Debit"
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Credit"
                    ),
                ),
                ("is_balanced", models.BooleanField(default=False, verbose_name="Is Balanced (Debits = Credits)")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True, verbose_name="Posted At")),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="general_ledger.accountingperiod",
                        verbose_name="Accounting Period",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to="branches.branch",
                        verbose_name="Branch Scope",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Posted By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "db_table": "gl_journal_entries",
                "ordering": ["-posting_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Line Description"),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Debit Amount"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Credit Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "base_debit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Base Currency Debit Amount",
                    ),
                ),
                (
                    "base_credit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Base Currency Credit Amount",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="general_ledger.chartofaccount",
                        verbose_name="Chart of Account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gl_journal_lines",
                        to="branches.branch",
                        verbose_name="Branch Scope",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="general_ledger.journalentry",
                        verbose_name="Journal Entry Header",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry Line",
                "verbose_name_plural": "Journal Entry Lines",
                "db_table": "gl_journal_entry_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountingperiod",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "fiscal_year", "period_number"),
                name="gl_period_tenant_company_yr_num_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(fields=["tenant", "account_type"], name="chart_of_ac_tenant__7ece12_idx"),
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(fields=["tenant", "account_code"], name="chart_of_ac_tenant__da7eea_idx"),
        ),
        migrations.AddConstraint(
            model_name="chartofaccount",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "account_code"), name="coa_tenant_company_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountmapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "purpose"), name="gl_mapping_tenant_company_purpose_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["tenant", "status"], name="gl_journal__tenant__303a19_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["tenant", "posting_date"], name="gl_journal__tenant__e9a3b0_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "reference_type", "reference_id"], name="gl_journal__tenant__e0cb11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("tenant", "journal_number"), name="gl_journal_tenant_number_uniq"
            ),
        ),
    ]
