# Generated by Django 5.2.17 on 2026-08-08 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Customer code")),
                ("customer_number", models.CharField(max_length=50, verbose_name="Customer number")),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("organization", "Organization"),
                            ("corporate", "Corporate"),
                            ("insurance", "Insurance Customer"),
                            ("walk_in", "Walk-in Customer"),
                            ("anonymous", "Anonymous Customer"),
                        ],
                        default="individual",
                        max_length=40,
                        verbose_name="Customer type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=100, verbose_name="First name")),
                ("middle_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Middle name")),
                ("last_name", models.CharField(blank=True, default="", max_length=100, verbose_name="Last name")),
                ("arabic_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Arabic name")),
                (
                    "english_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="English name"),
                ),
                (
                    "preferred_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Preferred name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("unspecified", "Unspecified"),
                        ],
                        default="unspecified",
                        max_length=20,
                        verbose_name="Gender",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="Date of birth")),
                ("national_id", models.CharField(blank=True, default="", max_length=100, verbose_name="National ID")),
                (
                    "passport_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Passport number"),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, default="Yemeni", max_length=100, verbose_name="Nationality"),
                ),
                ("occupation", models.CharField(blank=True, default="", max_length=150, verbose_name="Occupation")),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer_photos/", verbose_name="Profile photo"
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Primary phone")),
                (
                    "secondary_phone",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Secondary phone"),
                ),
                ("mobile", models.CharField(blank=True, default="", max_length=32, verbose_name="Mobile")),
                ("whatsapp", models.CharField(blank=True, default="", max_length=32, verbose_name="WhatsApp")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                (
                    "alternative_email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Alternative email"),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(default="phone", max_length=50, verbose_name="Preferred contact method"),
                ),
                (
                    "preferred_communication_language",
                    models.CharField(default="en", max_length=10, verbose_name="Preferred communication language"),
                ),
                (
                    "preferred_language",
                    models.CharField(default="en", max_length=10, verbose_name="Preferred language"),
                ),
                (
                    "preferred_currency",
                    models.CharField(default="YER", max_length=10, verbose_name="Preferred currency"),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(default="cash", max_length=50, verbose_name="Preferred payment method"),
                ),
                ("sms_notifications", models.BooleanField(default=True, verbose_name="SMS notifications enabled")),
                ("email_notifications", models.BooleanField(default=True, verbose_name="Email notifications enabled")),
                (
                    "whatsapp_notifications",
                    models.BooleanField(default=True, verbose_name="WhatsApp notifications enabled"),
                ),
                ("marketing_consent", models.BooleanField(default=False, verbose_name="Marketing consent")),
                (
                    "notification_preferences",
                    models.JSONField(blank=True, default=dict, verbose_name="Notification preferences"),
                ),
                ("credit_allowed", models.BooleanField(default=False, verbose_name="Credit allowed")),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Credit limit"),
                ),
                ("payment_terms", models.CharField(default="Immediate", max_length=100, verbose_name="Payment terms")),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Opening balance"),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Current balance"),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("warning", "Warning"),
                            ("blocked", "Blocked"),
                            ("suspended", "Suspended"),
                        ],
                        default="normal",
                        max_length=30,
                        verbose_name="Credit status",
                    ),
                ),
                (
                    "default_payment_method",
                    models.CharField(default="cash", max_length=50, verbose_name="Default payment method"),
                ),
                ("tax_category", models.CharField(default="standard", max_length=50, verbose_name="Tax category")),
                ("discount_eligibility", models.BooleanField(default=True, verbose_name="Discount eligibility")),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, verbose_name="Discount percentage"
                    ),
                ),
                ("price_list", models.CharField(blank=True, default="", max_length=100, verbose_name="Price list")),
                (
                    "customer_group",
                    models.CharField(db_index=True, default="regular", max_length=100, verbose_name="Customer group"),
                ),
                (
                    "customer_segment",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Customer segment"),
                ),
                (
                    "customer_category",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Customer category"),
                ),
                (
                    "loyalty_account_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Loyalty account number"),
                ),
                (
                    "loyalty_points_balance",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Loyalty points balance"
                    ),
                ),
                (
                    "membership_level",
                    models.CharField(default="bronze", max_length=50, verbose_name="Membership level"),
                ),
                (
                    "membership_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Membership number"),
                ),
                (
                    "loyalty_enrollment_date",
                    models.DateField(blank=True, null=True, verbose_name="Loyalty enrollment date"),
                ),
                (
                    "loyalty_expiration_date",
                    models.DateField(blank=True, null=True, verbose_name="Loyalty expiration date"),
                ),
                (
                    "insurance_provider_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Insurance provider name"),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Insurance policy number"),
                ),
                (
                    "insurance_member_number",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Insurance member number"),
                ),
                (
                    "insurance_coverage_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=30,
                        verbose_name="Insurance coverage status",
                    ),
                ),
                (
                    "insurance_coverage_start_date",
                    models.DateField(blank=True, null=True, verbose_name="Insurance coverage start date"),
                ),
                (
                    "insurance_coverage_end_date",
                    models.DateField(blank=True, null=True, verbose_name="Insurance coverage end date"),
                ),
                (
                    "insurance_category",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Insurance category"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "preferred_branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_customers",
                        to="branches.branch",
                        verbose_name="Preferred branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("billing", "Billing"),
                            ("delivery", "Delivery"),
                            ("other", "Other"),
                        ],
                        default="home",
                        max_length=30,
                        verbose_name="Address type",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Is primary address")),
                ("is_default_billing", models.BooleanField(default=False, verbose_name="Is default billing address")),
                (
                    "is_default_delivery",
                    models.BooleanField(default=False, verbose_name="Is default delivery address"),
                ),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("state", models.CharField(blank=True, default="", max_length=100, verbose_name="State")),
                ("city", models.CharField(default="Sanaa", max_length=100, verbose_name="City")),
                ("district", models.CharField(blank=True, default="", max_length=100, verbose_name="District")),
                ("street", models.CharField(blank=True, default="", max_length=255, verbose_name="Street")),
                ("building", models.CharField(blank=True, default="", max_length=100, verbose_name="Building")),
                ("postal_code", models.CharField(blank=True, default="", max_length=20, verbose_name="Postal code")),
                ("additional_info", models.TextField(blank=True, default="", verbose_name="Additional information")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True, verbose_name="Longitude"
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True, default="", verbose_name="Google Maps URL")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerMedicalProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                        verbose_name="Blood type",
                    ),
                ),
                ("allergies", models.JSONField(blank=True, default=list, verbose_name="Allergies list")),
                (
                    "chronic_conditions",
                    models.JSONField(blank=True, default=list, verbose_name="Chronic conditions list"),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Emergency contact name"),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=32, verbose_name="Emergency contact phone"),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Emergency contact relationship"
                    ),
                ),
                ("medical_notes", models.TextField(blank=True, default="", verbose_name="Medical notes")),
                (
                    "preferred_physician",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Preferred physician"),
                ),
                (
                    "preferred_pharmacy",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Preferred pharmacy"),
                ),
                ("insurance_info_notes", models.TextField(blank=True, default="", verbose_name="Insurance notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_profile",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Medical Profile",
                "verbose_name_plural": "Customer Medical Profiles",
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "status"], name="customers_c_tenant__d5e64f_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "customer_group"], name="customers_c_tenant__cafd8b_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "phone"], name="customers_c_tenant__6d2a04_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "mobile"], name="customers_c_tenant__b4bbcd_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "email"], name="customers_c_tenant__0aea56_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "national_id"], name="customers_c_tenant__b45108_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "passport_number"], name="customers_c_tenant__f77470_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tenant", "insurance_member_number"], name="customers_c_tenant__ebadca_idx"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(fields=("tenant", "code"), name="customers_customer_tenant_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "customer_number"), name="customers_customer_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(fields=["customer", "address_type"], name="customers_c_custome_7740eb_idx"),
        ),
        migrations.AddIndex(
            model_name="customeraddress",
            index=models.Index(fields=["tenant", "customer"], name="customers_c_tenant__99c0a9_idx"),
        ),
        migrations.AddIndex(
            model_name="customermedicalprofile",
            index=models.Index(fields=["tenant", "customer"], name="customers_c_tenant__951aee_idx"),
        ),
    ]
