# Generated by Django 5.2.17 on 2026-08-07 04:30

import apps.tenants.models.settings
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "domain_name",
                    models.CharField(db_index=True, max_length=255, unique=True, verbose_name="Domain name"),
                ),
                (
                    "domain_type",
                    models.CharField(
                        choices=[("primary", "Primary"), ("subdomain", "Subdomain"), ("custom", "Custom")],
                        default="subdomain",
                        max_length=30,
                        verbose_name="Domain type",
                    ),
                ),
                ("is_verified", models.BooleanField(db_index=True, default=False, verbose_name="Is verified")),
                (
                    "ssl_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("active", "Active"), ("failed", "Failed")],
                        default="pending",
                        max_length=30,
                        verbose_name="SSL status",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="Verification token"),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="Is primary domain")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Domain",
                "verbose_name_plural": "Tenant Domains",
                "ordering": ["-is_primary", "domain_name"],
            },
        ),
        migrations.CreateModel(
            name="TenantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("legal_name", models.CharField(max_length=200, verbose_name="Legal name")),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=150, verbose_name="Display name"),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("independent_pharmacy", "Independent Pharmacy"),
                            ("pharmacy_chain", "Pharmacy Chain"),
                            ("distributor_warehouse", "Distributor / Warehouse"),
                            ("clinic_pharmacy", "Clinic / Hospital Pharmacy"),
                        ],
                        default="independent_pharmacy",
                        max_length=50,
                        verbose_name="Business type",
                    ),
                ),
                ("tax_number", models.CharField(blank=True, default="", max_length=50, verbose_name="Tax number")),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="Registration number"),
                ),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("city", models.CharField(blank=True, default="", max_length=100, verbose_name="City")),
                ("address", models.TextField(blank=True, default="", verbose_name="Address")),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Phone")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, default="", verbose_name="Website")),
                ("logo", models.ImageField(blank=True, null=True, upload_to="tenant_logos/", verbose_name="Logo")),
                ("timezone", models.CharField(default="UTC", max_length=64, verbose_name="Timezone")),
                ("language", models.CharField(default="en", max_length=10, verbose_name="Language")),
                ("currency", models.CharField(default="YER", max_length=10, verbose_name="Currency")),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20, verbose_name="Date format")),
                ("time_format", models.CharField(default="24h", max_length=20, verbose_name="Time format")),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Fiscal year start month"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Profile",
                "verbose_name_plural": "Tenant Profiles",
                "ordering": ["legal_name"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("general_settings", models.JSONField(blank=True, default=dict, verbose_name="General settings")),
                ("localization", models.JSONField(blank=True, default=dict, verbose_name="Localization")),
                (
                    "tax_configuration",
                    models.JSONField(
                        blank=True,
                        default=apps.tenants.models.settings.default_tax_config,
                        verbose_name="Tax configuration",
                    ),
                ),
                ("business_hours", models.JSONField(blank=True, default=dict, verbose_name="Business hours")),
                (
                    "feature_flags",
                    models.JSONField(
                        blank=True,
                        default=apps.tenants.models.settings.default_feature_flags,
                        verbose_name="Feature flags",
                    ),
                ),
                (
                    "password_policy",
                    models.JSONField(
                        blank=True,
                        default=apps.tenants.models.settings.default_password_policy,
                        verbose_name="Password policy",
                    ),
                ),
                ("security_settings", models.JSONField(blank=True, default=dict, verbose_name="Security settings")),
                (
                    "notification_settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Notification settings"),
                ),
                ("theme", models.JSONField(blank=True, default=dict, verbose_name="Theme & branding")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
            },
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="trial",
                        max_length=50,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Billing cycle",
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Start date")),
                ("end_date", models.DateTimeField(blank=True, null=True, verbose_name="End date")),
                ("is_trial", models.BooleanField(default=True, verbose_name="Is trial")),
                ("grace_period_days", models.PositiveSmallIntegerField(default=7, verbose_name="Grace period days")),
                ("max_users", models.PositiveIntegerField(default=5, verbose_name="Maximum users limit")),
                ("max_branches", models.PositiveIntegerField(default=1, verbose_name="Maximum branches limit")),
                ("storage_limit_mb", models.PositiveIntegerField(default=1024, verbose_name="Storage limit (MB)")),
                (
                    "api_rate_limit_per_min",
                    models.PositiveIntegerField(default=1000, verbose_name="API rate limit per min"),
                ),
                ("feature_limits", models.JSONField(blank=True, default=dict, verbose_name="Feature limits")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="trialing",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Subscription",
                "verbose_name_plural": "Tenant Subscriptions",
            },
        ),
    ]
