# Generated by Django 5.2.17 on 2026-08-14 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportExportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("report_code", models.CharField(db_index=True, max_length=60, verbose_name="Report Code")),
                (
                    "report_category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales & POS Analytics"),
                            ("inventory", "Inventory & Valuation"),
                            ("purchasing", "Purchasing & Procurement"),
                            ("supplier", "Supplier & Accounts Payable"),
                            ("customer", "Customer & Accounts Receivable"),
                            ("financial", "General Ledger & Financial Statements"),
                            ("cash_bank", "Cash, Treasury & Bank Reconciliation"),
                            ("expense", "Expenses & Operating Costs"),
                            ("prescription", "Prescription & Clinical Dispensing"),
                            ("branch", "Branch Performance"),
                            ("employee", "Employee & Cashier Productivity"),
                            ("executive", "Executive Management Dashboard"),
                            ("reconciliation", "Cross-Subledger Reconciliation Audit"),
                        ],
                        default="sales",
                        max_length=35,
                        verbose_name="Report Category",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON Data Payload"),
                            ("csv", "Comma-Separated Values (CSV)"),
                            ("excel", "Microsoft Excel Spreadsheet (.xlsx)"),
                            ("pdf", "Portable Document Format (PDF)"),
                        ],
                        default="json",
                        max_length=20,
                        verbose_name="Export Format",
                    ),
                ),
                ("record_count", models.IntegerField(default=0, verbose_name="Exported Record Count")),
                (
                    "filters_applied",
                    models.JSONField(blank=True, default=dict, verbose_name="Filters Criteria Applied"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_export_logs",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Executed By User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export Log",
                "verbose_name_plural": "Report Export Logs",
                "db_table": "report_export_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "code",
                    models.CharField(db_index=True, max_length=60, verbose_name="Report Code (e.g. RPT-SAL-001)"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Report Title")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales", "Sales & POS Analytics"),
                            ("inventory", "Inventory & Valuation"),
                            ("purchasing", "Purchasing & Procurement"),
                            ("supplier", "Supplier & Accounts Payable"),
                            ("customer", "Customer & Accounts Receivable"),
                            ("financial", "General Ledger & Financial Statements"),
                            ("cash_bank", "Cash, Treasury & Bank Reconciliation"),
                            ("expense", "Expenses & Operating Costs"),
                            ("prescription", "Prescription & Clinical Dispensing"),
                            ("branch", "Branch Performance"),
                            ("employee", "Employee & Cashier Productivity"),
                            ("executive", "Executive Management Dashboard"),
                            ("reconciliation", "Cross-Subledger Reconciliation Audit"),
                        ],
                        db_index=True,
                        default="sales",
                        max_length=35,
                        verbose_name="Report Category",
                    ),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Report Description")),
                (
                    "required_permission",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Required RBAC Permission"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("is_financial", models.BooleanField(default=False, verbose_name="Is Authoritative Financial Report")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Definition",
                "verbose_name_plural": "Report Definitions",
                "db_table": "report_definitions",
                "ordering": ["category", "code"],
                "constraints": [models.UniqueConstraint(fields=("tenant", "code"), name="rpt_def_tenant_code_uniq")],
            },
        ),
    ]
