# Generated by Django 5.2.17 on 2026-08-08 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Warehouse code")),
                ("name", models.CharField(max_length=255, verbose_name="Warehouse name")),
                ("arabic_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Arabic name")),
                (
                    "english_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="English name"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Warehouse"),
                            ("pharmacy", "Pharmacy Warehouse"),
                            ("branch", "Branch Warehouse"),
                            ("distribution_center", "Distribution Center"),
                            ("cold_storage", "Cold Storage"),
                            ("controlled_drug", "Controlled Drug Storage"),
                            ("quarantine", "Quarantine Storage"),
                            ("returns", "Returns Storage"),
                            ("damaged", "Damaged Goods Storage"),
                            ("transit", "Transit Storage"),
                            ("virtual", "Virtual Warehouse"),
                            ("other", "Other Storage"),
                        ],
                        db_index=True,
                        default="main",
                        max_length=50,
                        verbose_name="Warehouse type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                            ("temporarily_closed", "Temporarily Closed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=32, verbose_name="Phone")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                ("address", models.CharField(blank=True, default="", max_length=255, verbose_name="Address")),
                ("country", models.CharField(default="Yemen", max_length=100, verbose_name="Country")),
                ("city", models.CharField(default="Sanaa", max_length=100, verbose_name="City")),
                ("district", models.CharField(blank=True, default="", max_length=100, verbose_name="District")),
                ("postal_code", models.CharField(blank=True, default="", max_length=20, verbose_name="Postal code")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True, verbose_name="Longitude"
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Working hours"),
                ),
                (
                    "is_default_receiving",
                    models.BooleanField(default=False, verbose_name="Is default receiving warehouse"),
                ),
                (
                    "is_default_returns",
                    models.BooleanField(default=False, verbose_name="Is default returns warehouse"),
                ),
                (
                    "is_default_quarantine",
                    models.BooleanField(default=False, verbose_name="Is default quarantine warehouse"),
                ),
                (
                    "is_default_damaged",
                    models.BooleanField(default=False, verbose_name="Is default damaged warehouse"),
                ),
                (
                    "is_default_cold",
                    models.BooleanField(default=False, verbose_name="Is default cold storage warehouse"),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Warehouse manager",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("code", models.CharField(max_length=50, verbose_name="Location code")),
                ("name", models.CharField(max_length=255, verbose_name="Location name")),
                ("arabic_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Arabic name")),
                (
                    "english_name",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="English name"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("zone", "Zone"),
                            ("aisle", "Aisle"),
                            ("rack", "Rack"),
                            ("shelf", "Shelf"),
                            ("bin", "Bin"),
                            ("room", "Room"),
                            ("cabinet", "Cabinet"),
                            ("cold_room", "Cold Room"),
                            ("freezer", "Freezer"),
                            ("quarantine_area", "Quarantine Area"),
                            ("returns_area", "Returns Area"),
                            ("damaged_area", "Damaged Area"),
                            ("other", "Other Location"),
                        ],
                        db_index=True,
                        default="zone",
                        max_length=50,
                        verbose_name="Location type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("blocked", "Blocked"),
                            ("full", "Full Capacity"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0, verbose_name="Display order")),
                (
                    "capacity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name="Maximum capacity"),
                ),
                (
                    "capacity_unit",
                    models.CharField(blank=True, default="units", max_length=50, verbose_name="Capacity unit"),
                ),
                (
                    "current_utilization",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=14, verbose_name="Current utilization"
                    ),
                ),
                (
                    "min_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Min temperature (°C)"
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Max temperature (°C)"
                    ),
                ),
                (
                    "min_humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Min relative humidity (%)"
                    ),
                ),
                (
                    "max_humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Max relative humidity (%)"
                    ),
                ),
                ("storage_conditions", models.JSONField(blank=True, default=list, verbose_name="Storage conditions")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="warehouses.storagelocation",
                        verbose_name="Parent location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Location",
                "verbose_name_plural": "Storage Locations",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["tenant", "status"], name="warehouses__tenant__a4dc5e_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["tenant", "warehouse_type"], name="warehouses__tenant__d03639_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["tenant", "company"], name="warehouses__tenant__3fb22d_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["tenant", "branch"], name="warehouses__tenant__0f4b73_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="warehouses_warehouse_tenant_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("tenant", "company", "name"), name="warehouses_warehouse_tenant_company_name_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(fields=["warehouse", "location_type"], name="warehouses__warehou_c7e9b8_idx"),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(fields=["warehouse", "parent"], name="warehouses__warehou_9acd34_idx"),
        ),
        migrations.AddIndex(
            model_name="storagelocation",
            index=models.Index(fields=["tenant", "warehouse"], name="warehouses__tenant__f8504b_idx"),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="warehouses_storagelocation_wh_code_uniq"
            ),
        ),
    ]
