# Generated by Django 5.2.17 on 2026-08-15 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android OS"),
                            ("ios", "Apple iOS"),
                            ("pwa", "Progressive Web App"),
                            ("desktop", "Dedicated Desktop Client"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Client Platform",
                    ),
                ),
                (
                    "min_version",
                    models.CharField(default="1.0.0", max_length=20, verbose_name="Minimum Supported Version"),
                ),
                (
                    "recommended_version",
                    models.CharField(default="1.0.0", max_length=20, verbose_name="Recommended Version"),
                ),
                ("is_force_update", models.BooleanField(default=False, verbose_name="Force App Update")),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Is Mobile Backend in Maintenance"),
                ),
                (
                    "maintenance_message",
                    models.TextField(blank=True, default="", verbose_name="Maintenance Notification Message"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile App Version Policy",
                "verbose_name_plural": "Mobile App Version Policies",
                "db_table": "mobile_app_versions",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "device_identifier",
                    models.CharField(db_index=True, max_length=120, verbose_name="Hardware / Installation UUID"),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android OS"),
                            ("ios", "Apple iOS"),
                            ("pwa", "Progressive Web App"),
                            ("desktop", "Dedicated Desktop Client"),
                        ],
                        default="android",
                        max_length=20,
                        verbose_name="Device Platform",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="1.0.0", max_length=30, verbose_name="Mobile App Version"),
                ),
                (
                    "os_version",
                    models.CharField(blank=True, default="", max_length=30, verbose_name="Operating System Version"),
                ),
                ("push_token", models.TextField(blank=True, default="", verbose_name="FCM / APNs Push Token")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Device Active")),
                (
                    "last_seen",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Last Seen Timestamp"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Device",
                "verbose_name_plural": "Mobile Devices",
                "db_table": "mobile_devices",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "device_identifier"), name="mobile_user_device_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="MobileSyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="Entity Domain Name (e.g. order, count_item)"
                    ),
                ),
                (
                    "client_mutation_id",
                    models.CharField(db_index=True, max_length=120, verbose_name="Client Generated Mutation UUID"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create Entity"),
                            ("update", "Update Entity"),
                            ("delete", "Delete Entity"),
                        ],
                        default="create",
                        max_length=20,
                        verbose_name="Sync Operation",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Client Mutation Payload")),
                ("client_version", models.IntegerField(default=1, verbose_name="Client Entity Version Snapshot")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Server Processing"),
                            ("applied", "Applied Successfully"),
                            ("conflict", "Version Conflict Detected"),
                            ("rejected", "Rejected by Business Logic"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Sync Processing Status",
                    ),
                ),
                ("conflict_reason", models.TextField(blank=True, default="", verbose_name="Conflict Error Details")),
                ("synced_at", models.DateTimeField(blank=True, null=True, verbose_name="Processed Timestamp")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_sync_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobile Sync Item",
                "verbose_name_plural": "Mobile Sync Queue",
                "db_table": "mobile_sync_queues",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client_mutation_id"), name="mobile_sync_client_mutation_uniq"
                    )
                ],
            },
        ),
    ]
