# Generated by Django 5.2.17 on 2026-08-11 00:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("customers", "0001_initial"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashRegister",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "register_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Register Number (REG)"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Register Counter Name")),
                (
                    "status",
                    models.CharField(
                        choices=[("closed", "Closed"), ("open", "Open / Operational"), ("maintenance", "Maintenance")],
                        db_index=True,
                        default="closed",
                        max_length=20,
                        verbose_name="Register Status",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Default Float Opening Balance",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Current Cash Balance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_registers",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_registers",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_registers",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Register",
                "verbose_name_plural": "Cash Registers",
                "db_table": "cash_registers",
                "ordering": ["register_number"],
            },
        ),
        migrations.CreateModel(
            name="RegisterSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "session_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Session Number (SES)"),
                ),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Opening Float Cash"
                    ),
                ),
                (
                    "cash_sales",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Cash Sales"
                    ),
                ),
                (
                    "cash_refunds",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Cash Refunds"
                    ),
                ),
                (
                    "cash_adjustments",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Cash Adjustments / Expenses",
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Expected Till Cash"
                    ),
                ),
                (
                    "actual_cash",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Counted Actual Cash"
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Variance Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Session Open"),
                            ("closed", "Session Closed"),
                            ("reconciled", "Reconciled & Audited"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                        verbose_name="Session Status",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True, verbose_name="Opened At")),
                ("closed_at", models.DateTimeField(blank=True, null=True, verbose_name="Closed At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "cash_register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="sales.cashregister",
                        verbose_name="Cash Register",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="register_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cashier",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Register Session",
                "verbose_name_plural": "Register Sessions",
                "db_table": "register_sessions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Invoice Number (INV)"),
                ),
                ("invoice_date", models.DateField(db_index=True, verbose_name="Invoice Date")),
                ("invoice_time", models.TimeField(verbose_name="Invoice Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Sale"),
                            ("held", "Held Sale / Cart"),
                            ("pending_payment", "Pending Payment"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("credit", "Customer Credit Sale"),
                            ("completed", "Completed Sale"),
                            ("cancelled", "Cancelled"),
                            ("voided", "Voided"),
                            ("refunded", "Fully Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Sales Status",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("overpaid", "Overpaid"),
                            ("credit", "Customer Account Balance Credit"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=30,
                        verbose_name="Payment Status",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Other Charges"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Grand Total"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Paid Amount"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Change Amount"
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Outstanding Balance"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed At")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True, verbose_name="Cancelled At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashier_sales_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cashier",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_invoices",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoices",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_invoices",
                        to="sales.registersession",
                        verbose_name="Cash Register Session",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salesperson_sales_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Salesperson",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Invoice",
                "verbose_name_plural": "Sales Invoices",
                "db_table": "sales_invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("1.0000"), max_digits=14, verbose_name="Sold Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Selling Price"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Discount %"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount Amount"
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5, verbose_name="Tax %"),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "line_subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Subtotal"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Grand Total"
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Historical Unit Cost"
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Line Gross Profit"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_lines",
                        to="inventory.batch",
                        verbose_name="Medicine Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesinvoice",
                        verbose_name="Sales Invoice",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_lines",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Invoice Line",
                "verbose_name_plural": "Sales Invoice Lines",
                "db_table": "sales_invoice_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Payment Number (PAY)"),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Tender"),
                            ("card", "Debit / Credit Card Terminal"),
                            ("bank_transfer", "Bank Electronic Transfer"),
                            ("mobile_wallet", "Mobile Payment Wallet"),
                            ("online_payment", "Online Payment Gateway"),
                            ("customer_credit", "Customer Credit Account"),
                            ("mixed_payment", "Mixed / Split Payment"),
                            ("other", "Other Payment Method"),
                        ],
                        default="cash",
                        max_length=30,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Payment Amount"
                    ),
                ),
                (
                    "tendered_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Cash Tendered Amount"
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Change Returned Amount",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Transaction / Card Reference"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("cancelled", "Cancelled"), ("reversed", "Reversed")],
                        db_index=True,
                        default="posted",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashier_sales_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sales.salesinvoice",
                        verbose_name="Sales Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Payment",
                "verbose_name_plural": "Sales Payments",
                "db_table": "sales_payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cashregister",
            constraint=models.UniqueConstraint(
                fields=("tenant", "register_number"), name="cash_register_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["tenant", "status"], name="sales_invoi_tenant__ea0900_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["tenant", "branch"], name="sales_invoi_tenant__e38812_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["tenant", "customer"], name="sales_invoi_tenant__80164e_idx"),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["tenant", "invoice_date"], name="sales_invoi_tenant__62aed4_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"), name="sales_invoice_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(fields=["tenant", "status"], name="sales_payme_tenant__177e1e_idx"),
        ),
        migrations.AddIndex(
            model_name="salespayment",
            index=models.Index(fields=["tenant", "payment_method"], name="sales_payme_tenant__1e55ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="salespayment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "payment_number"), name="sales_payment_tenant_number_uniq"
            ),
        ),
    ]
