# Generated by Django 5.2.17 on 2026-08-11 01:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoiceline",
            name="returned_quantity",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Returned Quantity"
            ),
        ),
    ]
