# Generated by Django 5.2.17 on 2026-08-11 01:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("customers", "0001_initial"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("sales", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("return_number", models.CharField(db_index=True, max_length=60, verbose_name="Return Number (CRT)")),
                ("return_date", models.DateField(db_index=True, verbose_name="Return Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Return Request"),
                            ("requested", "Requested / Submitted"),
                            ("pending_approval", "Pending Manager Approval"),
                            ("approved", "Approved"),
                            ("inspection", "Under Quality Inspection"),
                            ("partially_accepted", "Partially Accepted"),
                            ("accepted", "Fully Accepted"),
                            ("rejected", "Rejected"),
                            ("refund_pending", "Refund Pending Processing"),
                            ("refunded", "Refunded to Customer"),
                            ("store_credit_issued", "Store Credit Issued"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Return Status",
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("wrong_item", "Wrong Medicine / Item Dispensed"),
                            ("wrong_quantity", "Wrong Quantity Dispensed"),
                            ("damaged", "Damaged Product"),
                            ("defective", "Defective Product"),
                            ("expired", "Expired Medicine"),
                            ("near_expiry", "Near Expiry Date"),
                            ("allergic_reaction", "Adverse Effect / Allergic Reaction"),
                            ("customer_changed_mind", "Customer Changed Mind"),
                            ("quality_issue", "Quality Defect"),
                            ("packaging_damage", "Damaged Packaging"),
                            ("prescription_error", "Prescription Change / Error"),
                            ("duplicate_purchase", "Duplicate Purchase"),
                            ("other", "Other Reason"),
                        ],
                        default="other",
                        max_length=40,
                        verbose_name="Primary Return Reason",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Eligible Refund Amount",
                    ),
                ),
                (
                    "store_credit_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Issued Store Credit Amount",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_customer_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_returns",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_returns",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_returns",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_customer_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inspected By",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_customer_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_returns",
                        to="sales.salesinvoice",
                        verbose_name="Original Sales Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_returns",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Return",
                "verbose_name_plural": "Customer Returns",
                "db_table": "customer_returns",
                "ordering": ["-return_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("refund_number", models.CharField(db_index=True, max_length=60, verbose_name="Refund Number (REF)")),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Refund"),
                            ("card", "Debit / Credit Card Refund"),
                            ("bank_transfer", "Bank Electronic Transfer"),
                            ("mobile_wallet", "Mobile Wallet Refund"),
                            ("original_payment_method", "Original Payment Method"),
                            ("store_credit", "Customer Account Store Credit"),
                            ("other", "Other Refund Method"),
                        ],
                        default="cash",
                        max_length=30,
                        verbose_name="Refund Method",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Refund Amount"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Refund Reference / Gateway ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="completed",
                        max_length=20,
                        verbose_name="Refund Status",
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="Processed At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_customer_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_customer_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_refunds",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_customer_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Processed By",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="sales.salesinvoice",
                        verbose_name="Original Sales Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "customer_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="sales_returns.customerreturn",
                        verbose_name="Customer Return",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Refund",
                "verbose_name_plural": "Customer Refunds",
                "db_table": "customer_refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "original_sold_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Original Sold Quantity",
                    ),
                ),
                (
                    "previously_returned_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Previously Returned Quantity",
                    ),
                ),
                (
                    "returnable_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Returnable Quantity"
                    ),
                ),
                (
                    "requested_return_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Requested Return Quantity",
                    ),
                ),
                (
                    "accepted_return_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Accepted Return Quantity",
                    ),
                ),
                (
                    "rejected_return_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Rejected Return Quantity",
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "original_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Original Unit Selling Price",
                    ),
                ),
                (
                    "refund_unit_price",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Refund Unit Price"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount Portion"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Portion"
                    ),
                ),
                (
                    "refund_line_total",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Refund Line Grand Total",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sealed", "Sealed / Original Condition"),
                            ("opened", "Opened Outer Packaging"),
                            ("damaged", "Physically Damaged"),
                            ("expired", "Expired Date"),
                            ("refrigerated", "Cold Chain Refrigerated"),
                            ("temperature_damaged", "Temperature Excursion / Damaged Cold Chain"),
                            ("quarantined", "Quarantined Stock"),
                            ("recalled", "Pharmacovigilance Recalled Batch"),
                            ("unknown", "Unknown Condition"),
                        ],
                        default="sealed",
                        max_length=30,
                        verbose_name="Returned Product Condition",
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("wrong_item", "Wrong Medicine / Item Dispensed"),
                            ("wrong_quantity", "Wrong Quantity Dispensed"),
                            ("damaged", "Damaged Product"),
                            ("defective", "Defective Product"),
                            ("expired", "Expired Medicine"),
                            ("near_expiry", "Near Expiry Date"),
                            ("allergic_reaction", "Adverse Effect / Allergic Reaction"),
                            ("customer_changed_mind", "Customer Changed Mind"),
                            ("quality_issue", "Quality Defect"),
                            ("packaging_damage", "Damaged Packaging"),
                            ("prescription_error", "Prescription Change / Error"),
                            ("duplicate_purchase", "Duplicate Purchase"),
                            ("other", "Other Reason"),
                        ],
                        default="other",
                        max_length=40,
                        verbose_name="Line Return Reason",
                    ),
                ),
                (
                    "inspection_result",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted for Normal Resale Stock"),
                            ("rejected", "Rejected Return"),
                            ("quarantined", "Sent to Quarantine Stock"),
                            ("damaged", "Sent to Damaged Stock"),
                            ("expired", "Expired Stock Write-Off"),
                            ("recalled", "Batch Recall Hold"),
                        ],
                        default="accepted",
                        max_length=30,
                        verbose_name="Quality Inspection Result",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_return_lines",
                        to="inventory.batch",
                        verbose_name="Medicine Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales_returns.customerreturn",
                        verbose_name="Customer Return",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_return_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "sales_invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="sales.salesinvoiceline",
                        verbose_name="Original Sales Invoice Line",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_return_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_return_lines",
                        to="warehouses.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Return Line",
                "verbose_name_plural": "Customer Return Lines",
                "db_table": "customer_return_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(fields=["tenant", "status"], name="customer_re_tenant__a0223b_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(fields=["tenant", "sales_invoice"], name="customer_re_tenant__969437_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreturn",
            index=models.Index(fields=["tenant", "customer"], name="customer_re_tenant__e29ba6_idx"),
        ),
        migrations.AddConstraint(
            model_name="customerreturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "return_number"), name="customer_return_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="customerrefund",
            index=models.Index(fields=["tenant", "status"], name="customer_re_tenant__800a49_idx"),
        ),
        migrations.AddIndex(
            model_name="customerrefund",
            index=models.Index(fields=["tenant", "refund_method"], name="customer_re_tenant__2a5c12_idx"),
        ),
        migrations.AddConstraint(
            model_name="customerrefund",
            constraint=models.UniqueConstraint(
                fields=("tenant", "refund_number"), name="customer_refund_tenant_number_uniq"
            ),
        ),
    ]
