# Generated by Django 5.2.17 on 2026-08-11 22:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("customers", "0001_initial"),
        ("sales", "0002_salesinvoiceline_returned_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "payment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Payment Number (CPY)"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="Payment Received Date"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Payment"),
                            ("bank_transfer", "Bank Wire Transfer"),
                            ("card", "Credit / Debit Card"),
                            ("mobile_wallet", "Mobile Wallet"),
                            ("online_payment", "Online Payment Gateway"),
                            ("other", "Other Payment Method"),
                        ],
                        default="cash",
                        max_length=30,
                        verbose_name="Payment Method",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Payment Amount"
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Allocated Amount"
                    ),
                ),
                (
                    "unallocated_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unallocated Amount"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="External Check / Transaction Reference"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Payment"),
                            ("posted", "Posted Payment"),
                            ("partially_allocated", "Partially Allocated"),
                            ("fully_allocated", "Fully Allocated"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="posted",
                        max_length=30,
                        verbose_name="Payment Status",
                    ),
                ),
                ("reversed_at", models.DateTimeField(blank=True, null=True, verbose_name="Reversed At")),
                ("reversal_reason", models.TextField(blank=True, default="", verbose_name="Reversal Reason")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_customer_ar_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_ar_payments",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_ar_payments",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_payments",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_customer_ar_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Posted By",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_customer_ar_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reversed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Payment",
                "verbose_name_plural": "Customer Payments",
                "db_table": "customer_ar_payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerReceivable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "receivable_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Receivable Number (AR)"),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Original Obligation Amount",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Amount Paid"
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Store Credit / Return Credit Applied",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Refund Amount Applied",
                    ),
                ),
                (
                    "adjusted_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Adjusted Amount"
                    ),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Net Outstanding Balance",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Invoice / Obligation Date"),
                ),
                ("due_date", models.DateField(db_index=True, verbose_name="Payment Due Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open Receivable"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Fully Paid"),
                            ("overdue", "Overdue"),
                            ("disputed", "Disputed"),
                            ("credit", "Credit Balance"),
                            ("written_off", "Written Off"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                        verbose_name="AR Status",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_receivables",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_receivables",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_receivables",
                        to="customers.customer",
                        verbose_name="Customer / Client",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_receivables",
                        to="sales.salesinvoice",
                        verbose_name="Source Sales Invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Receivable",
                "verbose_name_plural": "Customer Receivables",
                "db_table": "customer_receivables",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Allocated Amount"
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(default=django.utils.timezone.now, verbose_name="Allocation Date"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="accounts_receivable.customerpayment",
                        verbose_name="Customer Payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="accounts_receivable.customerreceivable",
                        verbose_name="Customer Receivable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Payment Allocation",
                "verbose_name_plural": "Customer Payment Allocations",
                "db_table": "customer_ar_payment_allocations",
                "ordering": ["-allocation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "adjustment_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Adjustment Number (ADJ)"),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("debit_adjustment", "Debit Adjustment (Increase Receivable)"),
                            ("credit_adjustment", "Credit Adjustment (Decrease Receivable)"),
                            ("write_off", "Bad Debt Write-Off"),
                            ("correction", "Accounting Correction"),
                            ("other", "Other Adjustment"),
                        ],
                        default="credit_adjustment",
                        max_length=30,
                        verbose_name="Adjustment Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Adjustment Amount"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Adjustment Reason")),
                (
                    "reference",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="External Reference"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft Adjustment"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="approved",
                        max_length=30,
                        verbose_name="Adjustment Status",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ar_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By Manager",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_adjustments",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_adjustments",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="accounts_receivable.customerreceivable",
                        verbose_name="Receivable",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receivable Adjustment",
                "verbose_name_plural": "Receivable Adjustments",
                "db_table": "receivable_adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "dispute_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Dispute Number (DSP)"),
                ),
                (
                    "dispute_amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Disputed Amount"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_amount", "Incorrect Invoiced Amount"),
                            ("duplicate_charge", "Duplicate Invoiced Charge"),
                            ("return_pending", "Pending Return / Credit Note"),
                            ("payment_not_recorded", "Unrecorded Payment"),
                            ("price_dispute", "Unit Price Dispute"),
                            ("other", "Other Dispute Reason"),
                        ],
                        default="wrong_amount",
                        max_length=40,
                        verbose_name="Dispute Reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Dispute Open"),
                            ("under_review", "Under Financial Review"),
                            ("resolved_credit", "Resolved with Credit Adjustment"),
                            ("resolved_rejected", "Dispute Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=30,
                        verbose_name="Dispute Status",
                    ),
                ),
                ("description", models.TextField(verbose_name="Dispute Description")),
                ("resolution_notes", models.TextField(blank=True, default="", verbose_name="Resolution Notes")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="accounts_receivable.customerreceivable",
                        verbose_name="Receivable",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ar_disputes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receivable Dispute",
                "verbose_name_plural": "Receivable Disputes",
                "db_table": "receivable_disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableWriteOff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "write_off_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Write-Off Number (WOF)"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Write-Off Amount"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Write-Off Reason / Justification")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ar_write_offs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By Finance Manager",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_write_offs",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_write_offs",
                        to="customers.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="write_offs",
                        to="accounts_receivable.customerreceivable",
                        verbose_name="Receivable",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receivable Write-Off",
                "verbose_name_plural": "Receivable Write-Offs",
                "db_table": "receivable_write_offs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="customerpayment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "payment_number"), name="ar_payment_tenant_number_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="customerreceivable",
            index=models.Index(fields=["tenant", "status"], name="customer_re_tenant__db9b01_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreceivable",
            index=models.Index(fields=["tenant", "customer"], name="customer_re_tenant__3afbea_idx"),
        ),
        migrations.AddIndex(
            model_name="customerreceivable",
            index=models.Index(fields=["tenant", "due_date"], name="customer_re_tenant__7323b2_idx"),
        ),
        migrations.AddConstraint(
            model_name="customerreceivable",
            constraint=models.UniqueConstraint(
                fields=("tenant", "receivable_number"), name="ar_receivable_tenant_number_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivableadjustment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "adjustment_number"), name="ar_adjustment_tenant_number_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivabledispute",
            constraint=models.UniqueConstraint(
                fields=("tenant", "dispute_number"), name="ar_dispute_tenant_number_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivablewriteoff",
            constraint=models.UniqueConstraint(
                fields=("tenant", "write_off_number"), name="ar_write_off_tenant_number_uniq"
            ),
        ),
    ]
