# Generated by Django 5.2.17 on 2026-08-11 00:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("companies", "0001_initial"),
        ("core", "0003_tenant_deleted_at_tenant_is_deleted_tenant_owner_and_more"),
        ("goods_receipt", "0001_initial"),
        ("inventory", "0003_alter_inventorytransaction_batch"),
        ("medicines", "0003_medicine_category_ref_medicine_dosage_form_ref_and_more"),
        ("procurement", "0001_initial"),
        ("suppliers", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                ("return_number", models.CharField(db_index=True, max_length=60, verbose_name="Return Number (PRT)")),
                ("return_date", models.DateField(verbose_name="Return Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("requested", "Requested"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("picking", "Picking in Progress"),
                            ("ready_for_dispatch", "Ready for Dispatch"),
                            ("dispatched", "Dispatched to Supplier"),
                            ("in_transit", "In Transit"),
                            ("partially_accepted", "Partially Accepted by Supplier"),
                            ("accepted", "Fully Accepted by Supplier"),
                            ("rejected", "Rejected by Supplier"),
                            ("cancelled", "Cancelled"),
                            ("discrepancy", "Discrepancy Identified"),
                            ("closed", "Closed"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                        verbose_name="Return Status",
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged Product"),
                            ("expired", "Expired Product"),
                            ("near_expiry", "Near Expiry Short Shelf Life"),
                            ("wrong_item", "Wrong Medicine Delivered"),
                            ("wrong_batch", "Wrong Batch Delivered"),
                            ("wrong_quantity", "Wrong Quantity / Over-shipment"),
                            ("quality_defect", "Quality Defect / Manufacturing Defect"),
                            ("recalled", "Batch Recall Notice"),
                            ("temperature_excursion", "Cold Chain Temperature Excursion"),
                            ("supplier_error", "Supplier Dispatch Error"),
                            ("purchase_error", "Internal Ordering Error"),
                            ("customer_return", "Customer Return Back to Supplier"),
                            ("excess_stock", "Excess Stock Return"),
                            ("other", "Other Return Reason"),
                        ],
                        default="damaged",
                        max_length=40,
                        verbose_name="Primary Return Reason",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("emergency", "Emergency Purchase"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.000000"), max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Other Charges"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Grand Total"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100, verbose_name="Idempotency Key"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Approved At")),
                ("dispatched_at", models.DateTimeField(blank=True, null=True, verbose_name="Dispatched At")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Completed At")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_returns",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_returns",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatched_purchase_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dispatched By",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_returns",
                        to="goods_receipt.goodsreceipt",
                        verbose_name="Goods Receipt",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_returns",
                        to="procurement.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_received_purchase_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supplier Acceptance Logged By",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_purchase_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_returns",
                        to="warehouses.warehouse",
                        verbose_name="Source Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Return",
                "verbose_name_plural": "Purchase Returns",
                "db_table": "purchase_returns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "available_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Available Returnable Quantity",
                    ),
                ),
                (
                    "requested_return_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=14,
                        verbose_name="Requested Return Quantity",
                    ),
                ),
                (
                    "approved_return_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        max_digits=14,
                        verbose_name="Approved Return Quantity",
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Dispatched Quantity"
                    ),
                ),
                (
                    "supplier_accepted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Supplier Accepted Quantity",
                    ),
                ),
                (
                    "supplier_rejected_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Supplier Rejected Quantity",
                    ),
                ),
                (
                    "damaged_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Damaged Quantity"
                    ),
                ),
                ("unit", models.CharField(default="Pcs", max_length=50, verbose_name="Unit of Measure")),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Unit Return Cost"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Discount"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax"
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Total Line Value"
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged Product"),
                            ("expired", "Expired Product"),
                            ("near_expiry", "Near Expiry Short Shelf Life"),
                            ("wrong_item", "Wrong Medicine Delivered"),
                            ("wrong_batch", "Wrong Batch Delivered"),
                            ("wrong_quantity", "Wrong Quantity / Over-shipment"),
                            ("quality_defect", "Quality Defect / Manufacturing Defect"),
                            ("recalled", "Batch Recall Notice"),
                            ("temperature_excursion", "Cold Chain Temperature Excursion"),
                            ("supplier_error", "Supplier Dispatch Error"),
                            ("purchase_error", "Internal Ordering Error"),
                            ("customer_return", "Customer Return Back to Supplier"),
                            ("excess_stock", "Excess Stock Return"),
                            ("other", "Other Return Reason"),
                        ],
                        default="damaged",
                        max_length=40,
                        verbose_name="Return Reason",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("sealed", "Factory Sealed Original Packaging"),
                            ("opened", "Opened Box / Outer Seal Broken"),
                            ("damaged", "Visually Damaged / Leaking"),
                            ("expired", "Expired"),
                            ("quarantined", "Quarantined Batch"),
                            ("recalled", "Official Recall Notice"),
                            ("temperature_damaged", "Heat / Cold Excursion Damaged"),
                            ("other", "Other Condition"),
                        ],
                        default="sealed",
                        max_length=30,
                        verbose_name="Product Condition",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="inventory.batch",
                        verbose_name="Medicine Batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "goods_receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_return_lines",
                        to="goods_receipt.goodsreceiptline",
                        verbose_name="Source Goods Receipt Line",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="medicines.medicine",
                        verbose_name="Medicine",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_return_lines",
                        to="procurement.purchaseorderline",
                        verbose_name="Source Purchase Order Line",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchase_returns.purchasereturn",
                        verbose_name="Purchase Return",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_return_lines",
                        to="warehouses.storagelocation",
                        verbose_name="Source Storage Location",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Return Line",
                "verbose_name_plural": "Purchase Return Lines",
                "db_table": "purchase_return_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnDiscrepancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "discrepancy_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Discrepancy Number"),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Expected Quantity"
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Dispatched Quantity"
                    ),
                ),
                (
                    "supplier_accepted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Supplier Accepted Quantity",
                    ),
                ),
                (
                    "supplier_rejected_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=14,
                        verbose_name="Supplier Rejected Quantity",
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Quantity Difference"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("shortage", "Supplier Quantity Shortage"),
                            ("overage", "Supplier Quantity Overage"),
                            ("damage", "Damaged in Transport to Supplier"),
                            ("wrong_item", "Wrong Item Claimed by Supplier"),
                            ("wrong_batch", "Wrong Batch Claimed by Supplier"),
                            ("wrong_quantity", "Disputed Quantity Count"),
                            ("other", "Other Discrepancy Reason"),
                        ],
                        default="shortage",
                        max_length=30,
                        verbose_name="Discrepancy Reason",
                    ),
                ),
                ("evidence", models.TextField(blank=True, default="", verbose_name="Evidence / Supplier Statement")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Review"), ("reviewed", "Reviewed"), ("resolved", "Resolved")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="", verbose_name="Resolution Notes")),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="Resolved At")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancies_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="purchase_returns.purchasereturn",
                        verbose_name="Purchase Return",
                    ),
                ),
                (
                    "return_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="purchase_returns.purchasereturnline",
                        verbose_name="Return Line",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discrepancies_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Return Discrepancy",
                "verbose_name_plural": "Return Discrepancies",
                "db_table": "purchase_return_discrepancies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="Is deleted")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted at")),
                (
                    "credit_note_number",
                    models.CharField(db_index=True, max_length=60, verbose_name="Credit Note Number"),
                ),
                (
                    "supplier_reference",
                    models.CharField(blank=True, default="", max_length=100, verbose_name="Supplier Credit Note Ref."),
                ),
                (
                    "accepted_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Accepted Value"
                    ),
                ),
                (
                    "tax_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Tax Value"
                    ),
                ),
                (
                    "net_credit_value",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14, verbose_name="Net Credit Value"
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10, verbose_name="Currency Code")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Credit Note Generation"),
                            ("expected", "Expected Credit Note from Supplier"),
                            ("received", "Credit Note Received"),
                            ("posted", "Credit Note Posted to Accounts Payable"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "purchase_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="purchase_returns.purchasereturn",
                        verbose_name="Purchase Return",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="suppliers.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Credit Note",
                "verbose_name_plural": "Supplier Credit Notes",
                "db_table": "purchase_return_credit_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(fields=["tenant", "status"], name="purchase_re_tenant__b92f60_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(fields=["tenant", "supplier"], name="purchase_re_tenant__be6a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(fields=["tenant", "goods_receipt"], name="purchase_re_tenant__033a2c_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.UniqueConstraint(
                fields=("tenant", "return_number"), name="purchase_return_tenant_number_uniq"
            ),
        ),
    ]
